//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.31 at 09:11:08 PM CEST 
//


package org.example.model.fin.com.fundtech.scl.commontypes;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AliasStatusReason1Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="AliasStatusReason1Code"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="FROD"/&gt;
 *     &lt;enumeration value="CUST"/&gt;
 *     &lt;enumeration value="DECD"/&gt;
 *     &lt;enumeration value="LEGL"/&gt;
 *     &lt;enumeration value="PART"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "AliasStatusReason1Code")
@XmlEnum
public enum AliasStatusReason1Code {

    FROD,
    CUST,
    DECD,
    LEGL,
    PART;

    public String value() {
        return name();
    }

    public static AliasStatusReason1Code fromValue(String v) {
        return valueOf(v);
    }

}
