//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.31 at 09:11:08 PM CEST 
//


package org.example.model.fin.com.fundtech.scl.commontypes;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AuditTrailLineType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AuditTrailLineType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="F_AUDIT_ERROR_CODE" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="F_AUDIT_USER_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_AUDIT_TIME_STAMP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_AUDIT_END_DATE" type="{http://fundtech.com/SCL/CommonTypes}ISODateTime" minOccurs="0"/&gt;
 *         &lt;element name="F_AUDIT_UPDATE_DATE" type="{http://fundtech.com/SCL/CommonTypes}ISODateTime" minOccurs="0"/&gt;
 *         &lt;element name="F_AUDIT_ZONE_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_AUDIT_HIT_INFO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_AUDIT_STATUS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_AUDIT_ERROR_PARAMS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_AUDIT_IS_NEW" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="F_AUDIT_RELATED_FIELDS_DATA" type="{http://fundtech.com/SCL/CommonTypes}MsgTablesType" minOccurs="0"/&gt;
 *         &lt;element name="F_AUDIT_ERROR_DESC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AuditTrailLineType", propOrder = {
    "fauditerrorcode",
    "fauditusername",
    "faudittimestamp",
    "fauditenddate",
    "fauditupdatedate",
    "fauditzonecode",
    "faudithitinfo",
    "fauditstatus",
    "fauditerrorparams",
    "fauditisnew",
    "fauditrelatedfieldsdata",
    "fauditerrordesc"
})
public class AuditTrailLineType {

    @XmlElement(name = "F_AUDIT_ERROR_CODE")
    protected int fauditerrorcode;
    @XmlElement(name = "F_AUDIT_USER_NAME")
    protected String fauditusername;
    @XmlElement(name = "F_AUDIT_TIME_STAMP")
    protected String faudittimestamp;
    @XmlElement(name = "F_AUDIT_END_DATE")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fauditenddate;
    @XmlElement(name = "F_AUDIT_UPDATE_DATE")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fauditupdatedate;
    @XmlElement(name = "F_AUDIT_ZONE_CODE")
    protected String fauditzonecode;
    @XmlElement(name = "F_AUDIT_HIT_INFO")
    protected String faudithitinfo;
    @XmlElement(name = "F_AUDIT_STATUS")
    protected String fauditstatus;
    @XmlElement(name = "F_AUDIT_ERROR_PARAMS")
    protected String fauditerrorparams;
    @XmlElement(name = "F_AUDIT_IS_NEW")
    protected Boolean fauditisnew;
    @XmlElement(name = "F_AUDIT_RELATED_FIELDS_DATA")
    protected MsgTablesType fauditrelatedfieldsdata;
    @XmlElement(name = "F_AUDIT_ERROR_DESC")
    protected String fauditerrordesc;

    /**
     * Gets the value of the fauditerrorcode property.
     * 
     */
    public int getFAUDITERRORCODE() {
        return fauditerrorcode;
    }

    /**
     * Sets the value of the fauditerrorcode property.
     * 
     */
    public void setFAUDITERRORCODE(int value) {
        this.fauditerrorcode = value;
    }

    /**
     * Gets the value of the fauditusername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFAUDITUSERNAME() {
        return fauditusername;
    }

    /**
     * Sets the value of the fauditusername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFAUDITUSERNAME(String value) {
        this.fauditusername = value;
    }

    /**
     * Gets the value of the faudittimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFAUDITTIMESTAMP() {
        return faudittimestamp;
    }

    /**
     * Sets the value of the faudittimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFAUDITTIMESTAMP(String value) {
        this.faudittimestamp = value;
    }

    /**
     * Gets the value of the fauditenddate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFAUDITENDDATE() {
        return fauditenddate;
    }

    /**
     * Sets the value of the fauditenddate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFAUDITENDDATE(XMLGregorianCalendar value) {
        this.fauditenddate = value;
    }

    /**
     * Gets the value of the fauditupdatedate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFAUDITUPDATEDATE() {
        return fauditupdatedate;
    }

    /**
     * Sets the value of the fauditupdatedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFAUDITUPDATEDATE(XMLGregorianCalendar value) {
        this.fauditupdatedate = value;
    }

    /**
     * Gets the value of the fauditzonecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFAUDITZONECODE() {
        return fauditzonecode;
    }

    /**
     * Sets the value of the fauditzonecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFAUDITZONECODE(String value) {
        this.fauditzonecode = value;
    }

    /**
     * Gets the value of the faudithitinfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFAUDITHITINFO() {
        return faudithitinfo;
    }

    /**
     * Sets the value of the faudithitinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFAUDITHITINFO(String value) {
        this.faudithitinfo = value;
    }

    /**
     * Gets the value of the fauditstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFAUDITSTATUS() {
        return fauditstatus;
    }

    /**
     * Sets the value of the fauditstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFAUDITSTATUS(String value) {
        this.fauditstatus = value;
    }

    /**
     * Gets the value of the fauditerrorparams property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFAUDITERRORPARAMS() {
        return fauditerrorparams;
    }

    /**
     * Sets the value of the fauditerrorparams property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFAUDITERRORPARAMS(String value) {
        this.fauditerrorparams = value;
    }

    /**
     * Gets the value of the fauditisnew property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFAUDITISNEW() {
        return fauditisnew;
    }

    /**
     * Sets the value of the fauditisnew property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFAUDITISNEW(Boolean value) {
        this.fauditisnew = value;
    }

    /**
     * Gets the value of the fauditrelatedfieldsdata property.
     * 
     * @return
     *     possible object is
     *     {@link MsgTablesType }
     *     
     */
    public MsgTablesType getFAUDITRELATEDFIELDSDATA() {
        return fauditrelatedfieldsdata;
    }

    /**
     * Sets the value of the fauditrelatedfieldsdata property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgTablesType }
     *     
     */
    public void setFAUDITRELATEDFIELDSDATA(MsgTablesType value) {
        this.fauditrelatedfieldsdata = value;
    }

    /**
     * Gets the value of the fauditerrordesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFAUDITERRORDESC() {
        return fauditerrordesc;
    }

    /**
     * Sets the value of the fauditerrordesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFAUDITERRORDESC(String value) {
        this.fauditerrordesc = value;
    }

}
