//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.02 at 08:50:07 PM CEST 
//


package org.example.model.fin.com.fundtech.scl.commontypes;

import java.math.BigDecimal;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CycleSttlmLineType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CycleSttlmLineType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="F_CYCLE_STTLM_DEPARTMENT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CYCLE_STTLM_OFFICE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CYCLE_STTLM_CLEARING_SYSTEM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CYCLE_STTLM_MSG_USER_REFEREN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CYCLE_STTLM_TRANSACTION_DT" type="{http://fundtech.com/SCL/CommonTypes}ISODate" minOccurs="0"/&gt;
 *         &lt;element name="F_CYCLE_STTLM_BATCH_TM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CYCLE_STTLM_OUTWRD_DBT_CNT" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="F_CYCLE_STTLM_OUTWRD_DBT_AMT" type="{http://fundtech.com/SCL/CommonTypes}AmountType" minOccurs="0"/&gt;
 *         &lt;element name="F_CYCLE_STTLM_OUTWRD_DBT_ACCNT" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="F_CYCLE_STTLM_OUTWRD_DBT_ACAMT" type="{http://fundtech.com/SCL/CommonTypes}AmountType" minOccurs="0"/&gt;
 *         &lt;element name="F_CYCLE_STTLM_OUTWRD_DBT_RJCNT" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="F_CYCLE_STTLM_OUTWRD_DBT_RJAMT" type="{http://fundtech.com/SCL/CommonTypes}AmountType" minOccurs="0"/&gt;
 *         &lt;element name="F_CYCLE_STTLM_INWARD_CDT_COUNT" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="F_CYCLE_STTLM_INWARD_CRDT_AMT" type="{http://fundtech.com/SCL/CommonTypes}AmountType" minOccurs="0"/&gt;
 *         &lt;element name="F_CYCLE_STTLM_OUTWARD_RETU_CNT" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="F_CYCLE_STTLM_OUTWARD_RETU_AMT" type="{http://fundtech.com/SCL/CommonTypes}AmountType" minOccurs="0"/&gt;
 *         &lt;element name="F_CYCLE_STTLM_CALC_NET_SET_AMT" type="{http://fundtech.com/SCL/CommonTypes}AmountType" minOccurs="0"/&gt;
 *         &lt;element name="F_CYCLE_STTLM_SETTL_POSTING_TP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CYCLE_STTLM_POSTING_MSG_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CYCLE_STTLM_IS_NEW" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="F_CYCLE_STTLM_IS_UPDATED" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="F_CYCLE_STTLM_XML_MSG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CycleSttlmLineType", propOrder = {
    "fcyclesttlmdepartment",
    "fcyclesttlmoffice",
    "fcyclesttlmclearingsystem",
    "fcyclesttlmmsguserreferen",
    "fcyclesttlmtransactiondt",
    "fcyclesttlmbatchtm",
    "fcyclesttlmoutwrddbtcnt",
    "fcyclesttlmoutwrddbtamt",
    "fcyclesttlmoutwrddbtaccnt",
    "fcyclesttlmoutwrddbtacamt",
    "fcyclesttlmoutwrddbtrjcnt",
    "fcyclesttlmoutwrddbtrjamt",
    "fcyclesttlminwardcdtcount",
    "fcyclesttlminwardcrdtamt",
    "fcyclesttlmoutwardretucnt",
    "fcyclesttlmoutwardretuamt",
    "fcyclesttlmcalcnetsetamt",
    "fcyclesttlmsettlpostingtp",
    "fcyclesttlmpostingmsgid",
    "fcyclesttlmisnew",
    "fcyclesttlmisupdated",
    "fcyclesttlmxmlmsg"
})
public class CycleSttlmLineType {

    @XmlElement(name = "F_CYCLE_STTLM_DEPARTMENT")
    protected String fcyclesttlmdepartment;
    @XmlElement(name = "F_CYCLE_STTLM_OFFICE")
    protected String fcyclesttlmoffice;
    @XmlElement(name = "F_CYCLE_STTLM_CLEARING_SYSTEM")
    protected String fcyclesttlmclearingsystem;
    @XmlElement(name = "F_CYCLE_STTLM_MSG_USER_REFEREN")
    protected String fcyclesttlmmsguserreferen;
    @XmlElement(name = "F_CYCLE_STTLM_TRANSACTION_DT")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fcyclesttlmtransactiondt;
    @XmlElement(name = "F_CYCLE_STTLM_BATCH_TM")
    protected String fcyclesttlmbatchtm;
    @XmlElement(name = "F_CYCLE_STTLM_OUTWRD_DBT_CNT")
    protected Integer fcyclesttlmoutwrddbtcnt;
    @XmlElement(name = "F_CYCLE_STTLM_OUTWRD_DBT_AMT")
    protected BigDecimal fcyclesttlmoutwrddbtamt;
    @XmlElement(name = "F_CYCLE_STTLM_OUTWRD_DBT_ACCNT")
    protected Integer fcyclesttlmoutwrddbtaccnt;
    @XmlElement(name = "F_CYCLE_STTLM_OUTWRD_DBT_ACAMT")
    protected BigDecimal fcyclesttlmoutwrddbtacamt;
    @XmlElement(name = "F_CYCLE_STTLM_OUTWRD_DBT_RJCNT")
    protected Integer fcyclesttlmoutwrddbtrjcnt;
    @XmlElement(name = "F_CYCLE_STTLM_OUTWRD_DBT_RJAMT")
    protected BigDecimal fcyclesttlmoutwrddbtrjamt;
    @XmlElement(name = "F_CYCLE_STTLM_INWARD_CDT_COUNT")
    protected Integer fcyclesttlminwardcdtcount;
    @XmlElement(name = "F_CYCLE_STTLM_INWARD_CRDT_AMT")
    protected BigDecimal fcyclesttlminwardcrdtamt;
    @XmlElement(name = "F_CYCLE_STTLM_OUTWARD_RETU_CNT")
    protected Integer fcyclesttlmoutwardretucnt;
    @XmlElement(name = "F_CYCLE_STTLM_OUTWARD_RETU_AMT")
    protected BigDecimal fcyclesttlmoutwardretuamt;
    @XmlElement(name = "F_CYCLE_STTLM_CALC_NET_SET_AMT")
    protected BigDecimal fcyclesttlmcalcnetsetamt;
    @XmlElement(name = "F_CYCLE_STTLM_SETTL_POSTING_TP")
    protected String fcyclesttlmsettlpostingtp;
    @XmlElement(name = "F_CYCLE_STTLM_POSTING_MSG_ID")
    protected String fcyclesttlmpostingmsgid;
    @XmlElement(name = "F_CYCLE_STTLM_IS_NEW")
    protected Boolean fcyclesttlmisnew;
    @XmlElement(name = "F_CYCLE_STTLM_IS_UPDATED")
    protected Boolean fcyclesttlmisupdated;
    @XmlElement(name = "F_CYCLE_STTLM_XML_MSG")
    protected String fcyclesttlmxmlmsg;

    /**
     * Gets the value of the fcyclesttlmdepartment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCYCLESTTLMDEPARTMENT() {
        return fcyclesttlmdepartment;
    }

    /**
     * Sets the value of the fcyclesttlmdepartment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCYCLESTTLMDEPARTMENT(String value) {
        this.fcyclesttlmdepartment = value;
    }

    /**
     * Gets the value of the fcyclesttlmoffice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCYCLESTTLMOFFICE() {
        return fcyclesttlmoffice;
    }

    /**
     * Sets the value of the fcyclesttlmoffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCYCLESTTLMOFFICE(String value) {
        this.fcyclesttlmoffice = value;
    }

    /**
     * Gets the value of the fcyclesttlmclearingsystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCYCLESTTLMCLEARINGSYSTEM() {
        return fcyclesttlmclearingsystem;
    }

    /**
     * Sets the value of the fcyclesttlmclearingsystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCYCLESTTLMCLEARINGSYSTEM(String value) {
        this.fcyclesttlmclearingsystem = value;
    }

    /**
     * Gets the value of the fcyclesttlmmsguserreferen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCYCLESTTLMMSGUSERREFEREN() {
        return fcyclesttlmmsguserreferen;
    }

    /**
     * Sets the value of the fcyclesttlmmsguserreferen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCYCLESTTLMMSGUSERREFEREN(String value) {
        this.fcyclesttlmmsguserreferen = value;
    }

    /**
     * Gets the value of the fcyclesttlmtransactiondt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFCYCLESTTLMTRANSACTIONDT() {
        return fcyclesttlmtransactiondt;
    }

    /**
     * Sets the value of the fcyclesttlmtransactiondt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFCYCLESTTLMTRANSACTIONDT(XMLGregorianCalendar value) {
        this.fcyclesttlmtransactiondt = value;
    }

    /**
     * Gets the value of the fcyclesttlmbatchtm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCYCLESTTLMBATCHTM() {
        return fcyclesttlmbatchtm;
    }

    /**
     * Sets the value of the fcyclesttlmbatchtm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCYCLESTTLMBATCHTM(String value) {
        this.fcyclesttlmbatchtm = value;
    }

    /**
     * Gets the value of the fcyclesttlmoutwrddbtcnt property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFCYCLESTTLMOUTWRDDBTCNT() {
        return fcyclesttlmoutwrddbtcnt;
    }

    /**
     * Sets the value of the fcyclesttlmoutwrddbtcnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFCYCLESTTLMOUTWRDDBTCNT(Integer value) {
        this.fcyclesttlmoutwrddbtcnt = value;
    }

    /**
     * Gets the value of the fcyclesttlmoutwrddbtamt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFCYCLESTTLMOUTWRDDBTAMT() {
        return fcyclesttlmoutwrddbtamt;
    }

    /**
     * Sets the value of the fcyclesttlmoutwrddbtamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFCYCLESTTLMOUTWRDDBTAMT(BigDecimal value) {
        this.fcyclesttlmoutwrddbtamt = value;
    }

    /**
     * Gets the value of the fcyclesttlmoutwrddbtaccnt property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFCYCLESTTLMOUTWRDDBTACCNT() {
        return fcyclesttlmoutwrddbtaccnt;
    }

    /**
     * Sets the value of the fcyclesttlmoutwrddbtaccnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFCYCLESTTLMOUTWRDDBTACCNT(Integer value) {
        this.fcyclesttlmoutwrddbtaccnt = value;
    }

    /**
     * Gets the value of the fcyclesttlmoutwrddbtacamt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFCYCLESTTLMOUTWRDDBTACAMT() {
        return fcyclesttlmoutwrddbtacamt;
    }

    /**
     * Sets the value of the fcyclesttlmoutwrddbtacamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFCYCLESTTLMOUTWRDDBTACAMT(BigDecimal value) {
        this.fcyclesttlmoutwrddbtacamt = value;
    }

    /**
     * Gets the value of the fcyclesttlmoutwrddbtrjcnt property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFCYCLESTTLMOUTWRDDBTRJCNT() {
        return fcyclesttlmoutwrddbtrjcnt;
    }

    /**
     * Sets the value of the fcyclesttlmoutwrddbtrjcnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFCYCLESTTLMOUTWRDDBTRJCNT(Integer value) {
        this.fcyclesttlmoutwrddbtrjcnt = value;
    }

    /**
     * Gets the value of the fcyclesttlmoutwrddbtrjamt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFCYCLESTTLMOUTWRDDBTRJAMT() {
        return fcyclesttlmoutwrddbtrjamt;
    }

    /**
     * Sets the value of the fcyclesttlmoutwrddbtrjamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFCYCLESTTLMOUTWRDDBTRJAMT(BigDecimal value) {
        this.fcyclesttlmoutwrddbtrjamt = value;
    }

    /**
     * Gets the value of the fcyclesttlminwardcdtcount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFCYCLESTTLMINWARDCDTCOUNT() {
        return fcyclesttlminwardcdtcount;
    }

    /**
     * Sets the value of the fcyclesttlminwardcdtcount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFCYCLESTTLMINWARDCDTCOUNT(Integer value) {
        this.fcyclesttlminwardcdtcount = value;
    }

    /**
     * Gets the value of the fcyclesttlminwardcrdtamt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFCYCLESTTLMINWARDCRDTAMT() {
        return fcyclesttlminwardcrdtamt;
    }

    /**
     * Sets the value of the fcyclesttlminwardcrdtamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFCYCLESTTLMINWARDCRDTAMT(BigDecimal value) {
        this.fcyclesttlminwardcrdtamt = value;
    }

    /**
     * Gets the value of the fcyclesttlmoutwardretucnt property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFCYCLESTTLMOUTWARDRETUCNT() {
        return fcyclesttlmoutwardretucnt;
    }

    /**
     * Sets the value of the fcyclesttlmoutwardretucnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFCYCLESTTLMOUTWARDRETUCNT(Integer value) {
        this.fcyclesttlmoutwardretucnt = value;
    }

    /**
     * Gets the value of the fcyclesttlmoutwardretuamt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFCYCLESTTLMOUTWARDRETUAMT() {
        return fcyclesttlmoutwardretuamt;
    }

    /**
     * Sets the value of the fcyclesttlmoutwardretuamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFCYCLESTTLMOUTWARDRETUAMT(BigDecimal value) {
        this.fcyclesttlmoutwardretuamt = value;
    }

    /**
     * Gets the value of the fcyclesttlmcalcnetsetamt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFCYCLESTTLMCALCNETSETAMT() {
        return fcyclesttlmcalcnetsetamt;
    }

    /**
     * Sets the value of the fcyclesttlmcalcnetsetamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFCYCLESTTLMCALCNETSETAMT(BigDecimal value) {
        this.fcyclesttlmcalcnetsetamt = value;
    }

    /**
     * Gets the value of the fcyclesttlmsettlpostingtp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCYCLESTTLMSETTLPOSTINGTP() {
        return fcyclesttlmsettlpostingtp;
    }

    /**
     * Sets the value of the fcyclesttlmsettlpostingtp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCYCLESTTLMSETTLPOSTINGTP(String value) {
        this.fcyclesttlmsettlpostingtp = value;
    }

    /**
     * Gets the value of the fcyclesttlmpostingmsgid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCYCLESTTLMPOSTINGMSGID() {
        return fcyclesttlmpostingmsgid;
    }

    /**
     * Sets the value of the fcyclesttlmpostingmsgid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCYCLESTTLMPOSTINGMSGID(String value) {
        this.fcyclesttlmpostingmsgid = value;
    }

    /**
     * Gets the value of the fcyclesttlmisnew property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFCYCLESTTLMISNEW() {
        return fcyclesttlmisnew;
    }

    /**
     * Sets the value of the fcyclesttlmisnew property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFCYCLESTTLMISNEW(Boolean value) {
        this.fcyclesttlmisnew = value;
    }

    /**
     * Gets the value of the fcyclesttlmisupdated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFCYCLESTTLMISUPDATED() {
        return fcyclesttlmisupdated;
    }

    /**
     * Sets the value of the fcyclesttlmisupdated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFCYCLESTTLMISUPDATED(Boolean value) {
        this.fcyclesttlmisupdated = value;
    }

    /**
     * Gets the value of the fcyclesttlmxmlmsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCYCLESTTLMXMLMSG() {
        return fcyclesttlmxmlmsg;
    }

    /**
     * Sets the value of the fcyclesttlmxmlmsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCYCLESTTLMXMLMSG(String value) {
        this.fcyclesttlmxmlmsg = value;
    }

}
