//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.02 at 08:50:07 PM CEST 
//


package org.example.model.fin.com.fundtech.scl.commontypes;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExtnSuppDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtnSuppDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="X_CDT_TRNF_INFO_XS_CDI_POSTING_OPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="X_CDT_TRNF_INFO_XS_DESC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="X_CDT_TRNF_INFO_XS_COUNTER_PARTY_CCY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="X_CDT_TRNF_INFO_XS_REG_RPRTNG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="X_CDT_TRNF_INFO_XS_ITEMIZED_ORDER_ACNT_REF" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="X_CDT_TRNF_INFO_XS_INSTR_TXT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="X_INITG_PTY_XS_SOURCE_SYS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="X_INITG_PTY_XS_INSTR_REF" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="X_INITG_PTY_XS_FNDT_OPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="X_INITG_PTY_XS_CLR_HS_SVC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="X_INITG_PTY_XS_COLLCT_ON_SUCCES_MDL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="X_INITG_PTY_XS_FILE_FRMT_VER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="X_INITG_PTY_XS_COUNTRY_BIC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="X_INITG_PTY_XS_COLLTN_MODL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="X_CDT_TRNF_INFO_XS_CDI_REF" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="X_CDT_TRNF_INFO_XS_INSTR_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtnSuppDataType", propOrder = {

})
public class ExtnSuppDataType {

    @XmlElement(name = "X_CDT_TRNF_INFO_XS_CDI_POSTING_OPTION")
    protected String xcdttrnfinfoxscdipostingoption;
    @XmlElement(name = "X_CDT_TRNF_INFO_XS_DESC")
    protected String xcdttrnfinfoxsdesc;
    @XmlElement(name = "X_CDT_TRNF_INFO_XS_COUNTER_PARTY_CCY")
    protected String xcdttrnfinfoxscounterpartyccy;
    @XmlElement(name = "X_CDT_TRNF_INFO_XS_REG_RPRTNG")
    protected String xcdttrnfinfoxsregrprtng;
    @XmlElement(name = "X_CDT_TRNF_INFO_XS_ITEMIZED_ORDER_ACNT_REF")
    protected String xcdttrnfinfoxsitemizedorderacntref;
    @XmlElement(name = "X_CDT_TRNF_INFO_XS_INSTR_TXT")
    protected String xcdttrnfinfoxsinstrtxt;
    @XmlElement(name = "X_INITG_PTY_XS_SOURCE_SYS")
    protected String xinitgptyxssourcesys;
    @XmlElement(name = "X_INITG_PTY_XS_INSTR_REF")
    protected String xinitgptyxsinstrref;
    @XmlElement(name = "X_INITG_PTY_XS_FNDT_OPTION")
    protected String xinitgptyxsfndtoption;
    @XmlElement(name = "X_INITG_PTY_XS_CLR_HS_SVC")
    protected String xinitgptyxsclrhssvc;
    @XmlElement(name = "X_INITG_PTY_XS_COLLCT_ON_SUCCES_MDL")
    protected String xinitgptyxscollctonsuccesmdl;
    @XmlElement(name = "X_INITG_PTY_XS_FILE_FRMT_VER")
    protected String xinitgptyxsfilefrmtver;
    @XmlElement(name = "X_INITG_PTY_XS_COUNTRY_BIC")
    protected String xinitgptyxscountrybic;
    @XmlElement(name = "X_INITG_PTY_XS_COLLTN_MODL")
    protected String xinitgptyxscolltnmodl;
    @XmlElement(name = "X_CDT_TRNF_INFO_XS_CDI_REF")
    protected String xcdttrnfinfoxscdiref;
    @XmlElement(name = "X_CDT_TRNF_INFO_XS_INSTR_CODE")
    protected String xcdttrnfinfoxsinstrcode;

    /**
     * Gets the value of the xcdttrnfinfoxscdipostingoption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXCDTTRNFINFOXSCDIPOSTINGOPTION() {
        return xcdttrnfinfoxscdipostingoption;
    }

    /**
     * Sets the value of the xcdttrnfinfoxscdipostingoption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXCDTTRNFINFOXSCDIPOSTINGOPTION(String value) {
        this.xcdttrnfinfoxscdipostingoption = value;
    }

    /**
     * Gets the value of the xcdttrnfinfoxsdesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXCDTTRNFINFOXSDESC() {
        return xcdttrnfinfoxsdesc;
    }

    /**
     * Sets the value of the xcdttrnfinfoxsdesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXCDTTRNFINFOXSDESC(String value) {
        this.xcdttrnfinfoxsdesc = value;
    }

    /**
     * Gets the value of the xcdttrnfinfoxscounterpartyccy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXCDTTRNFINFOXSCOUNTERPARTYCCY() {
        return xcdttrnfinfoxscounterpartyccy;
    }

    /**
     * Sets the value of the xcdttrnfinfoxscounterpartyccy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXCDTTRNFINFOXSCOUNTERPARTYCCY(String value) {
        this.xcdttrnfinfoxscounterpartyccy = value;
    }

    /**
     * Gets the value of the xcdttrnfinfoxsregrprtng property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXCDTTRNFINFOXSREGRPRTNG() {
        return xcdttrnfinfoxsregrprtng;
    }

    /**
     * Sets the value of the xcdttrnfinfoxsregrprtng property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXCDTTRNFINFOXSREGRPRTNG(String value) {
        this.xcdttrnfinfoxsregrprtng = value;
    }

    /**
     * Gets the value of the xcdttrnfinfoxsitemizedorderacntref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXCDTTRNFINFOXSITEMIZEDORDERACNTREF() {
        return xcdttrnfinfoxsitemizedorderacntref;
    }

    /**
     * Sets the value of the xcdttrnfinfoxsitemizedorderacntref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXCDTTRNFINFOXSITEMIZEDORDERACNTREF(String value) {
        this.xcdttrnfinfoxsitemizedorderacntref = value;
    }

    /**
     * Gets the value of the xcdttrnfinfoxsinstrtxt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXCDTTRNFINFOXSINSTRTXT() {
        return xcdttrnfinfoxsinstrtxt;
    }

    /**
     * Sets the value of the xcdttrnfinfoxsinstrtxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXCDTTRNFINFOXSINSTRTXT(String value) {
        this.xcdttrnfinfoxsinstrtxt = value;
    }

    /**
     * Gets the value of the xinitgptyxssourcesys property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXINITGPTYXSSOURCESYS() {
        return xinitgptyxssourcesys;
    }

    /**
     * Sets the value of the xinitgptyxssourcesys property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXINITGPTYXSSOURCESYS(String value) {
        this.xinitgptyxssourcesys = value;
    }

    /**
     * Gets the value of the xinitgptyxsinstrref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXINITGPTYXSINSTRREF() {
        return xinitgptyxsinstrref;
    }

    /**
     * Sets the value of the xinitgptyxsinstrref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXINITGPTYXSINSTRREF(String value) {
        this.xinitgptyxsinstrref = value;
    }

    /**
     * Gets the value of the xinitgptyxsfndtoption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXINITGPTYXSFNDTOPTION() {
        return xinitgptyxsfndtoption;
    }

    /**
     * Sets the value of the xinitgptyxsfndtoption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXINITGPTYXSFNDTOPTION(String value) {
        this.xinitgptyxsfndtoption = value;
    }

    /**
     * Gets the value of the xinitgptyxsclrhssvc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXINITGPTYXSCLRHSSVC() {
        return xinitgptyxsclrhssvc;
    }

    /**
     * Sets the value of the xinitgptyxsclrhssvc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXINITGPTYXSCLRHSSVC(String value) {
        this.xinitgptyxsclrhssvc = value;
    }

    /**
     * Gets the value of the xinitgptyxscollctonsuccesmdl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXINITGPTYXSCOLLCTONSUCCESMDL() {
        return xinitgptyxscollctonsuccesmdl;
    }

    /**
     * Sets the value of the xinitgptyxscollctonsuccesmdl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXINITGPTYXSCOLLCTONSUCCESMDL(String value) {
        this.xinitgptyxscollctonsuccesmdl = value;
    }

    /**
     * Gets the value of the xinitgptyxsfilefrmtver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXINITGPTYXSFILEFRMTVER() {
        return xinitgptyxsfilefrmtver;
    }

    /**
     * Sets the value of the xinitgptyxsfilefrmtver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXINITGPTYXSFILEFRMTVER(String value) {
        this.xinitgptyxsfilefrmtver = value;
    }

    /**
     * Gets the value of the xinitgptyxscountrybic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXINITGPTYXSCOUNTRYBIC() {
        return xinitgptyxscountrybic;
    }

    /**
     * Sets the value of the xinitgptyxscountrybic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXINITGPTYXSCOUNTRYBIC(String value) {
        this.xinitgptyxscountrybic = value;
    }

    /**
     * Gets the value of the xinitgptyxscolltnmodl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXINITGPTYXSCOLLTNMODL() {
        return xinitgptyxscolltnmodl;
    }

    /**
     * Sets the value of the xinitgptyxscolltnmodl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXINITGPTYXSCOLLTNMODL(String value) {
        this.xinitgptyxscolltnmodl = value;
    }

    /**
     * Gets the value of the xcdttrnfinfoxscdiref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXCDTTRNFINFOXSCDIREF() {
        return xcdttrnfinfoxscdiref;
    }

    /**
     * Sets the value of the xcdttrnfinfoxscdiref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXCDTTRNFINFOXSCDIREF(String value) {
        this.xcdttrnfinfoxscdiref = value;
    }

    /**
     * Gets the value of the xcdttrnfinfoxsinstrcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXCDTTRNFINFOXSINSTRCODE() {
        return xcdttrnfinfoxsinstrcode;
    }

    /**
     * Sets the value of the xcdttrnfinfoxsinstrcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXCDTTRNFINFOXSINSTRCODE(String value) {
        this.xcdttrnfinfoxsinstrcode = value;
    }

}
