//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.02 at 08:50:07 PM CEST 
//


package org.example.model.fin.com.fundtech.scl.commontypes;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FndtMsgExtensionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FndtMsgExtensionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="MsgFees" type="{http://fundtech.com/SCL/CommonTypes}MsgFeesType" minOccurs="0"/&gt;
 *         &lt;element name="MsgNotes" type="{http://fundtech.com/SCL/CommonTypes}MsgNotesType" minOccurs="0"/&gt;
 *         &lt;element name="MsgRates" type="{http://fundtech.com/SCL/CommonTypes}ForwardContractType" minOccurs="0"/&gt;
 *         &lt;element name="Advising" type="{http://fundtech.com/SCL/CommonTypes}AdvisingType" minOccurs="0"/&gt;
 *         &lt;element name="MsgErrors" type="{http://fundtech.com/SCL/CommonTypes}MsgErrorsType" minOccurs="0"/&gt;
 *         &lt;element name="AuditTrail" type="{http://fundtech.com/SCL/CommonTypes}AuditTrailType" minOccurs="0"/&gt;
 *         &lt;element name="PostingRestrictions" type="{http://fundtech.com/SCL/CommonTypes}PostingRestrictionsType" minOccurs="0"/&gt;
 *         &lt;element name="SpecialInstructions" type="{http://fundtech.com/SCL/CommonTypes}SpecialInstructionsType" minOccurs="0"/&gt;
 *         &lt;element name="ExchrateRtr" type="{http://fundtech.com/SCL/CommonTypes}ExchrateRtrType" minOccurs="0"/&gt;
 *         &lt;element name="MFamily" type="{http://fundtech.com/SCL/CommonTypes}MFamilyType" minOccurs="0"/&gt;
 *         &lt;element name="CycleSttlm" type="{http://fundtech.com/SCL/CommonTypes}CycleSttlmType" minOccurs="0"/&gt;
 *         &lt;element name="PaymentAddressRequest" type="{http://fundtech.com/SCL/CommonTypes}PaymentAddressRequest" minOccurs="0"/&gt;
 *         &lt;element name="PaymentAddressResponse" type="{http://fundtech.com/SCL/CommonTypes}PaymentAddressResponse" minOccurs="0"/&gt;
 *         &lt;element name="AliasResolutionResponse" type="{http://fundtech.com/SCL/CommonTypes}AliasResolutionResponse" minOccurs="0"/&gt;
 *         &lt;element name="MOP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Office" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ProcessingPersistentInfo" type="{http://fundtech.com/SCL/CommonTypes}ProcessingPersistentInfoType" minOccurs="0"/&gt;
 *         &lt;element name="paymentGeneralInfo" type="{http://fundtech.com/SCL/CommonTypes}PaymentGeneralInfoType" minOccurs="0"/&gt;
 *         &lt;element name="ExchangeRateInfo" type="{http://fundtech.com/SCL/CommonTypes}ExchangeRateInfoType" minOccurs="0"/&gt;
 *         &lt;element name="XMLPersistentInfo" type="{http://fundtech.com/SCL/CommonTypes}XMLPersistentInfoType" minOccurs="0"/&gt;
 *         &lt;element name="ExtnSuppData" type="{http://fundtech.com/SCL/CommonTypes}ExtnSuppDataType" minOccurs="0"/&gt;
 *         &lt;element name="CutoffInfo" type="{http://fundtech.com/SCL/CommonTypes}CutoffInfoType" minOccurs="0"/&gt;
 *         &lt;element name="OperationalSection" type="{http://fundtech.com/SCL/CommonTypes}OperationalSectionType" minOccurs="0"/&gt;
 *         &lt;element name="AdditionalInformation" type="{http://fundtech.com/SCL/CommonTypes}AdditionalInformationType" minOccurs="0"/&gt;
 *         &lt;element name="MsgPosting" type="{http://fundtech.com/SCL/CommonTypes}PostingInfoType" minOccurs="0"/&gt;
 *         &lt;element name="BalanceCheckInf" type="{http://fundtech.com/SCL/CommonTypes}BalanceCheckInfType" minOccurs="0"/&gt;
 *         &lt;element name="LiquidityCheckInf" type="{http://fundtech.com/SCL/CommonTypes}LiquidityCheckInfType" minOccurs="0"/&gt;
 *         &lt;element name="PaymentContact" type="{http://fundtech.com/SCL/CommonTypes}PaymentContactType" minOccurs="0"/&gt;
 *         &lt;element name="UserDefinedFields" type="{http://fundtech.com/SCL/CommonTypes}UserDefinedFieldsType" minOccurs="0"/&gt;
 *         &lt;element name="pricingInfo" type="{http://fundtech.com/SCL/CommonTypes}pricingInfo" minOccurs="0"/&gt;
 *         &lt;element name="AdditionalInterfaceFields" type="{http://fundtech.com/SCL/CommonTypes}InterfaceFieldsType" minOccurs="0"/&gt;
 *         &lt;element name="InterfacesSection" type="{http://fundtech.com/SCL/CommonTypes}InterfacesSectionType" minOccurs="0"/&gt;
 *         &lt;element name="QaInfo" type="{http://fundtech.com/SCL/CommonTypes}QaInfoType" minOccurs="0"/&gt;
 *         &lt;element name="ProcessingTransientInfo" type="{http://fundtech.com/SCL/CommonTypes}ProcessingTransientInfoType" minOccurs="0"/&gt;
 *         &lt;element name="Monitors" type="{http://fundtech.com/SCL/CommonTypes}MonitorsType" minOccurs="0"/&gt;
 *         &lt;element name="ReferenceData" type="{http://fundtech.com/SCL/CommonTypes}ReferenceDataType" minOccurs="0"/&gt;
 *         &lt;element name="BinrayContent" type="{http://fundtech.com/SCL/CommonTypes}BinrayContentType" minOccurs="0"/&gt;
 *         &lt;element name="InternalSuppData" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FndtMsgExtensionType", propOrder = {

})
public class FndtMsgExtensionType {

    @XmlElement(name = "MsgFees")
    protected MsgFeesType msgFees;
    @XmlElement(name = "MsgNotes")
    protected MsgNotesType msgNotes;
    @XmlElement(name = "MsgRates")
    protected ForwardContractType msgRates;
    @XmlElement(name = "Advising")
    protected AdvisingType advising;
    @XmlElement(name = "MsgErrors")
    protected MsgErrorsType msgErrors;
    @XmlElement(name = "AuditTrail")
    protected AuditTrailType auditTrail;
    @XmlElement(name = "PostingRestrictions")
    protected PostingRestrictionsType postingRestrictions;
    @XmlElement(name = "SpecialInstructions")
    protected SpecialInstructionsType specialInstructions;
    @XmlElement(name = "ExchrateRtr")
    protected ExchrateRtrType exchrateRtr;
    @XmlElement(name = "MFamily")
    protected MFamilyType mFamily;
    @XmlElement(name = "CycleSttlm")
    protected CycleSttlmType cycleSttlm;
    @XmlElement(name = "PaymentAddressRequest")
    protected PaymentAddressRequest paymentAddressRequest;
    @XmlElement(name = "PaymentAddressResponse")
    protected PaymentAddressResponse paymentAddressResponse;
    @XmlElement(name = "AliasResolutionResponse")
    protected AliasResolutionResponse aliasResolutionResponse;
    @XmlElement(name = "MOP")
    protected String mop;
    @XmlElement(name = "Office")
    protected String office;
    @XmlElement(name = "ProcessingPersistentInfo")
    protected ProcessingPersistentInfoType processingPersistentInfo;
    protected PaymentGeneralInfoType paymentGeneralInfo;
    @XmlElement(name = "ExchangeRateInfo")
    protected ExchangeRateInfoType exchangeRateInfo;
    @XmlElement(name = "XMLPersistentInfo")
    protected XMLPersistentInfoType xmlPersistentInfo;
    @XmlElement(name = "ExtnSuppData")
    protected ExtnSuppDataType extnSuppData;
    @XmlElement(name = "CutoffInfo")
    protected CutoffInfoType cutoffInfo;
    @XmlElement(name = "OperationalSection")
    protected OperationalSectionType operationalSection;
    @XmlElement(name = "AdditionalInformation")
    protected AdditionalInformationType additionalInformation;
    @XmlElement(name = "MsgPosting")
    protected PostingInfoType msgPosting;
    @XmlElement(name = "BalanceCheckInf")
    protected BalanceCheckInfType balanceCheckInf;
    @XmlElement(name = "LiquidityCheckInf")
    protected LiquidityCheckInfType liquidityCheckInf;
    @XmlElement(name = "PaymentContact")
    protected PaymentContactType paymentContact;
    @XmlElement(name = "UserDefinedFields")
    protected UserDefinedFieldsType userDefinedFields;
    protected PricingInfo pricingInfo;
    @XmlElement(name = "AdditionalInterfaceFields")
    protected InterfaceFieldsType additionalInterfaceFields;
    @XmlElement(name = "InterfacesSection")
    protected InterfacesSectionType interfacesSection;
    @XmlElement(name = "QaInfo")
    protected QaInfoType qaInfo;
    @XmlElement(name = "ProcessingTransientInfo")
    protected ProcessingTransientInfoType processingTransientInfo;
    @XmlElement(name = "Monitors")
    protected MonitorsType monitors;
    @XmlElement(name = "ReferenceData")
    protected ReferenceDataType referenceData;
    @XmlElement(name = "BinrayContent")
    protected BinrayContentType binrayContent;
    @XmlElement(name = "InternalSuppData")
    protected Object internalSuppData;

    /**
     * Gets the value of the msgFees property.
     * 
     * @return
     *     possible object is
     *     {@link MsgFeesType }
     *     
     */
    public MsgFeesType getMsgFees() {
        return msgFees;
    }

    /**
     * Sets the value of the msgFees property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgFeesType }
     *     
     */
    public void setMsgFees(MsgFeesType value) {
        this.msgFees = value;
    }

    /**
     * Gets the value of the msgNotes property.
     * 
     * @return
     *     possible object is
     *     {@link MsgNotesType }
     *     
     */
    public MsgNotesType getMsgNotes() {
        return msgNotes;
    }

    /**
     * Sets the value of the msgNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgNotesType }
     *     
     */
    public void setMsgNotes(MsgNotesType value) {
        this.msgNotes = value;
    }

    /**
     * Gets the value of the msgRates property.
     * 
     * @return
     *     possible object is
     *     {@link ForwardContractType }
     *     
     */
    public ForwardContractType getMsgRates() {
        return msgRates;
    }

    /**
     * Sets the value of the msgRates property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForwardContractType }
     *     
     */
    public void setMsgRates(ForwardContractType value) {
        this.msgRates = value;
    }

    /**
     * Gets the value of the advising property.
     * 
     * @return
     *     possible object is
     *     {@link AdvisingType }
     *     
     */
    public AdvisingType getAdvising() {
        return advising;
    }

    /**
     * Sets the value of the advising property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdvisingType }
     *     
     */
    public void setAdvising(AdvisingType value) {
        this.advising = value;
    }

    /**
     * Gets the value of the msgErrors property.
     * 
     * @return
     *     possible object is
     *     {@link MsgErrorsType }
     *     
     */
    public MsgErrorsType getMsgErrors() {
        return msgErrors;
    }

    /**
     * Sets the value of the msgErrors property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgErrorsType }
     *     
     */
    public void setMsgErrors(MsgErrorsType value) {
        this.msgErrors = value;
    }

    /**
     * Gets the value of the auditTrail property.
     * 
     * @return
     *     possible object is
     *     {@link AuditTrailType }
     *     
     */
    public AuditTrailType getAuditTrail() {
        return auditTrail;
    }

    /**
     * Sets the value of the auditTrail property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuditTrailType }
     *     
     */
    public void setAuditTrail(AuditTrailType value) {
        this.auditTrail = value;
    }

    /**
     * Gets the value of the postingRestrictions property.
     * 
     * @return
     *     possible object is
     *     {@link PostingRestrictionsType }
     *     
     */
    public PostingRestrictionsType getPostingRestrictions() {
        return postingRestrictions;
    }

    /**
     * Sets the value of the postingRestrictions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PostingRestrictionsType }
     *     
     */
    public void setPostingRestrictions(PostingRestrictionsType value) {
        this.postingRestrictions = value;
    }

    /**
     * Gets the value of the specialInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link SpecialInstructionsType }
     *     
     */
    public SpecialInstructionsType getSpecialInstructions() {
        return specialInstructions;
    }

    /**
     * Sets the value of the specialInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecialInstructionsType }
     *     
     */
    public void setSpecialInstructions(SpecialInstructionsType value) {
        this.specialInstructions = value;
    }

    /**
     * Gets the value of the exchrateRtr property.
     * 
     * @return
     *     possible object is
     *     {@link ExchrateRtrType }
     *     
     */
    public ExchrateRtrType getExchrateRtr() {
        return exchrateRtr;
    }

    /**
     * Sets the value of the exchrateRtr property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExchrateRtrType }
     *     
     */
    public void setExchrateRtr(ExchrateRtrType value) {
        this.exchrateRtr = value;
    }

    /**
     * Gets the value of the mFamily property.
     * 
     * @return
     *     possible object is
     *     {@link MFamilyType }
     *     
     */
    public MFamilyType getMFamily() {
        return mFamily;
    }

    /**
     * Sets the value of the mFamily property.
     * 
     * @param value
     *     allowed object is
     *     {@link MFamilyType }
     *     
     */
    public void setMFamily(MFamilyType value) {
        this.mFamily = value;
    }

    /**
     * Gets the value of the cycleSttlm property.
     * 
     * @return
     *     possible object is
     *     {@link CycleSttlmType }
     *     
     */
    public CycleSttlmType getCycleSttlm() {
        return cycleSttlm;
    }

    /**
     * Sets the value of the cycleSttlm property.
     * 
     * @param value
     *     allowed object is
     *     {@link CycleSttlmType }
     *     
     */
    public void setCycleSttlm(CycleSttlmType value) {
        this.cycleSttlm = value;
    }

    /**
     * Gets the value of the paymentAddressRequest property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentAddressRequest }
     *     
     */
    public PaymentAddressRequest getPaymentAddressRequest() {
        return paymentAddressRequest;
    }

    /**
     * Sets the value of the paymentAddressRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentAddressRequest }
     *     
     */
    public void setPaymentAddressRequest(PaymentAddressRequest value) {
        this.paymentAddressRequest = value;
    }

    /**
     * Gets the value of the paymentAddressResponse property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentAddressResponse }
     *     
     */
    public PaymentAddressResponse getPaymentAddressResponse() {
        return paymentAddressResponse;
    }

    /**
     * Sets the value of the paymentAddressResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentAddressResponse }
     *     
     */
    public void setPaymentAddressResponse(PaymentAddressResponse value) {
        this.paymentAddressResponse = value;
    }

    /**
     * Gets the value of the aliasResolutionResponse property.
     * 
     * @return
     *     possible object is
     *     {@link AliasResolutionResponse }
     *     
     */
    public AliasResolutionResponse getAliasResolutionResponse() {
        return aliasResolutionResponse;
    }

    /**
     * Sets the value of the aliasResolutionResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link AliasResolutionResponse }
     *     
     */
    public void setAliasResolutionResponse(AliasResolutionResponse value) {
        this.aliasResolutionResponse = value;
    }

    /**
     * Gets the value of the mop property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOP() {
        return mop;
    }

    /**
     * Sets the value of the mop property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOP(String value) {
        this.mop = value;
    }

    /**
     * Gets the value of the office property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOffice() {
        return office;
    }

    /**
     * Sets the value of the office property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOffice(String value) {
        this.office = value;
    }

    /**
     * Gets the value of the processingPersistentInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessingPersistentInfoType }
     *     
     */
    public ProcessingPersistentInfoType getProcessingPersistentInfo() {
        return processingPersistentInfo;
    }

    /**
     * Sets the value of the processingPersistentInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessingPersistentInfoType }
     *     
     */
    public void setProcessingPersistentInfo(ProcessingPersistentInfoType value) {
        this.processingPersistentInfo = value;
    }

    /**
     * Gets the value of the paymentGeneralInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentGeneralInfoType }
     *     
     */
    public PaymentGeneralInfoType getPaymentGeneralInfo() {
        return paymentGeneralInfo;
    }

    /**
     * Sets the value of the paymentGeneralInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentGeneralInfoType }
     *     
     */
    public void setPaymentGeneralInfo(PaymentGeneralInfoType value) {
        this.paymentGeneralInfo = value;
    }

    /**
     * Gets the value of the exchangeRateInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ExchangeRateInfoType }
     *     
     */
    public ExchangeRateInfoType getExchangeRateInfo() {
        return exchangeRateInfo;
    }

    /**
     * Sets the value of the exchangeRateInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExchangeRateInfoType }
     *     
     */
    public void setExchangeRateInfo(ExchangeRateInfoType value) {
        this.exchangeRateInfo = value;
    }

    /**
     * Gets the value of the xmlPersistentInfo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLPersistentInfoType }
     *     
     */
    public XMLPersistentInfoType getXMLPersistentInfo() {
        return xmlPersistentInfo;
    }

    /**
     * Sets the value of the xmlPersistentInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLPersistentInfoType }
     *     
     */
    public void setXMLPersistentInfo(XMLPersistentInfoType value) {
        this.xmlPersistentInfo = value;
    }

    /**
     * Gets the value of the extnSuppData property.
     * 
     * @return
     *     possible object is
     *     {@link ExtnSuppDataType }
     *     
     */
    public ExtnSuppDataType getExtnSuppData() {
        return extnSuppData;
    }

    /**
     * Sets the value of the extnSuppData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtnSuppDataType }
     *     
     */
    public void setExtnSuppData(ExtnSuppDataType value) {
        this.extnSuppData = value;
    }

    /**
     * Gets the value of the cutoffInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CutoffInfoType }
     *     
     */
    public CutoffInfoType getCutoffInfo() {
        return cutoffInfo;
    }

    /**
     * Sets the value of the cutoffInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CutoffInfoType }
     *     
     */
    public void setCutoffInfo(CutoffInfoType value) {
        this.cutoffInfo = value;
    }

    /**
     * Gets the value of the operationalSection property.
     * 
     * @return
     *     possible object is
     *     {@link OperationalSectionType }
     *     
     */
    public OperationalSectionType getOperationalSection() {
        return operationalSection;
    }

    /**
     * Sets the value of the operationalSection property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationalSectionType }
     *     
     */
    public void setOperationalSection(OperationalSectionType value) {
        this.operationalSection = value;
    }

    /**
     * Gets the value of the additionalInformation property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalInformationType }
     *     
     */
    public AdditionalInformationType getAdditionalInformation() {
        return additionalInformation;
    }

    /**
     * Sets the value of the additionalInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalInformationType }
     *     
     */
    public void setAdditionalInformation(AdditionalInformationType value) {
        this.additionalInformation = value;
    }

    /**
     * Gets the value of the msgPosting property.
     * 
     * @return
     *     possible object is
     *     {@link PostingInfoType }
     *     
     */
    public PostingInfoType getMsgPosting() {
        return msgPosting;
    }

    /**
     * Sets the value of the msgPosting property.
     * 
     * @param value
     *     allowed object is
     *     {@link PostingInfoType }
     *     
     */
    public void setMsgPosting(PostingInfoType value) {
        this.msgPosting = value;
    }

    /**
     * Gets the value of the balanceCheckInf property.
     * 
     * @return
     *     possible object is
     *     {@link BalanceCheckInfType }
     *     
     */
    public BalanceCheckInfType getBalanceCheckInf() {
        return balanceCheckInf;
    }

    /**
     * Sets the value of the balanceCheckInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link BalanceCheckInfType }
     *     
     */
    public void setBalanceCheckInf(BalanceCheckInfType value) {
        this.balanceCheckInf = value;
    }

    /**
     * Gets the value of the liquidityCheckInf property.
     * 
     * @return
     *     possible object is
     *     {@link LiquidityCheckInfType }
     *     
     */
    public LiquidityCheckInfType getLiquidityCheckInf() {
        return liquidityCheckInf;
    }

    /**
     * Sets the value of the liquidityCheckInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link LiquidityCheckInfType }
     *     
     */
    public void setLiquidityCheckInf(LiquidityCheckInfType value) {
        this.liquidityCheckInf = value;
    }

    /**
     * Gets the value of the paymentContact property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentContactType }
     *     
     */
    public PaymentContactType getPaymentContact() {
        return paymentContact;
    }

    /**
     * Sets the value of the paymentContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentContactType }
     *     
     */
    public void setPaymentContact(PaymentContactType value) {
        this.paymentContact = value;
    }

    /**
     * Gets the value of the userDefinedFields property.
     * 
     * @return
     *     possible object is
     *     {@link UserDefinedFieldsType }
     *     
     */
    public UserDefinedFieldsType getUserDefinedFields() {
        return userDefinedFields;
    }

    /**
     * Sets the value of the userDefinedFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserDefinedFieldsType }
     *     
     */
    public void setUserDefinedFields(UserDefinedFieldsType value) {
        this.userDefinedFields = value;
    }

    /**
     * Gets the value of the pricingInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PricingInfo }
     *     
     */
    public PricingInfo getPricingInfo() {
        return pricingInfo;
    }

    /**
     * Sets the value of the pricingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PricingInfo }
     *     
     */
    public void setPricingInfo(PricingInfo value) {
        this.pricingInfo = value;
    }

    /**
     * Gets the value of the additionalInterfaceFields property.
     * 
     * @return
     *     possible object is
     *     {@link InterfaceFieldsType }
     *     
     */
    public InterfaceFieldsType getAdditionalInterfaceFields() {
        return additionalInterfaceFields;
    }

    /**
     * Sets the value of the additionalInterfaceFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterfaceFieldsType }
     *     
     */
    public void setAdditionalInterfaceFields(InterfaceFieldsType value) {
        this.additionalInterfaceFields = value;
    }

    /**
     * Gets the value of the interfacesSection property.
     * 
     * @return
     *     possible object is
     *     {@link InterfacesSectionType }
     *     
     */
    public InterfacesSectionType getInterfacesSection() {
        return interfacesSection;
    }

    /**
     * Sets the value of the interfacesSection property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterfacesSectionType }
     *     
     */
    public void setInterfacesSection(InterfacesSectionType value) {
        this.interfacesSection = value;
    }

    /**
     * Gets the value of the qaInfo property.
     * 
     * @return
     *     possible object is
     *     {@link QaInfoType }
     *     
     */
    public QaInfoType getQaInfo() {
        return qaInfo;
    }

    /**
     * Sets the value of the qaInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link QaInfoType }
     *     
     */
    public void setQaInfo(QaInfoType value) {
        this.qaInfo = value;
    }

    /**
     * Gets the value of the processingTransientInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessingTransientInfoType }
     *     
     */
    public ProcessingTransientInfoType getProcessingTransientInfo() {
        return processingTransientInfo;
    }

    /**
     * Sets the value of the processingTransientInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessingTransientInfoType }
     *     
     */
    public void setProcessingTransientInfo(ProcessingTransientInfoType value) {
        this.processingTransientInfo = value;
    }

    /**
     * Gets the value of the monitors property.
     * 
     * @return
     *     possible object is
     *     {@link MonitorsType }
     *     
     */
    public MonitorsType getMonitors() {
        return monitors;
    }

    /**
     * Sets the value of the monitors property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonitorsType }
     *     
     */
    public void setMonitors(MonitorsType value) {
        this.monitors = value;
    }

    /**
     * Gets the value of the referenceData property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceDataType }
     *     
     */
    public ReferenceDataType getReferenceData() {
        return referenceData;
    }

    /**
     * Sets the value of the referenceData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceDataType }
     *     
     */
    public void setReferenceData(ReferenceDataType value) {
        this.referenceData = value;
    }

    /**
     * Gets the value of the binrayContent property.
     * 
     * @return
     *     possible object is
     *     {@link BinrayContentType }
     *     
     */
    public BinrayContentType getBinrayContent() {
        return binrayContent;
    }

    /**
     * Sets the value of the binrayContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BinrayContentType }
     *     
     */
    public void setBinrayContent(BinrayContentType value) {
        this.binrayContent = value;
    }

    /**
     * Gets the value of the internalSuppData property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getInternalSuppData() {
        return internalSuppData;
    }

    /**
     * Sets the value of the internalSuppData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setInternalSuppData(Object value) {
        this.internalSuppData = value;
    }

}
