//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.31 at 09:11:08 PM CEST 
//


package org.example.model.fin.com.fundtech.scl.commontypes;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InternalRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InternalRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sessionId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="MID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Extn" type="{http://fundtech.com/SCL/CommonTypes}FndtMsgExtensionType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InternalRequestType", propOrder = {
    "sessionId",
    "mid",
    "extn"
})
public class InternalRequestType {

    @XmlElement(required = true)
    protected String sessionId;
    @XmlElement(name = "MID", required = true)
    protected String mid;
    @XmlElement(name = "Extn")
    protected FndtMsgExtensionType extn;

    /**
     * Gets the value of the sessionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * Sets the value of the sessionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSessionId(String value) {
        this.sessionId = value;
    }

    /**
     * Gets the value of the mid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMID() {
        return mid;
    }

    /**
     * Sets the value of the mid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMID(String value) {
        this.mid = value;
    }

    /**
     * Gets the value of the extn property.
     * 
     * @return
     *     possible object is
     *     {@link FndtMsgExtensionType }
     *     
     */
    public FndtMsgExtensionType getExtn() {
        return extn;
    }

    /**
     * Sets the value of the extn property.
     * 
     * @param value
     *     allowed object is
     *     {@link FndtMsgExtensionType }
     *     
     */
    public void setExtn(FndtMsgExtensionType value) {
        this.extn = value;
    }

}
