//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.02 at 08:50:07 PM CEST 
//


package org.example.model.fin.com.fundtech.scl.commontypes;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for M_CDT_CUST_PROFILEType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="M_CDT_CUST_PROFILEType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="F_CDTR_FULL_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDTR_SHORT_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_SEGMENT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_FEE_ACCOUNT_OFFICE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_FEE_ACCOUNT_CCY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_ABA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_BASE_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_CLEARING_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_COUNTRYCODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_CUST_CATEGORY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_CUST_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_CUST_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_CUST_TYPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_DEPARTMENT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_FEE_ACCOUNT_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_FROMREASON" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_IBAN_BANK_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_OWNERSHIP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_RESIDENCY1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_PROFESSION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_REG_REPORT1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_REG_REPORT2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_ALIAS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_STOPFLAGFROM" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_STOPFLAGTO" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_SWIFT_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_TOREASON" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_STATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_CITY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_ZIP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_ADDRESS1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_ADDRESS2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_ADDRESS3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_ADDRESS4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_ADDRESS5" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_ADDRESS6" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_ADDRESS7" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_BUILDING_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_BUILDING_ROOM_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_BUILDING_FLOOR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_POST_OFFICE_BOX" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_TOWN_LOCATION_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_DISTRICT_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_ADDRESS_TYPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_PSTLADR_ADDRESS_TYPE_PRTRY_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_PSTLADR_ADDRESS_TYPE_PRTRY_ISSUER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_PSTLADR_ADDRESS_TYPE_PRTRY_SCHME_NM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_STREET_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_BUILDING_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_DIVISION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_SUB_DIVISION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_CUST_COUNTRY_SUB_DIVISION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "M_CDT_CUST_PROFILEType", propOrder = {

})
public class MCDTCUSTPROFILEType {

    @XmlElement(name = "F_CDTR_FULL_NAME")
    protected String fcdtrfullname;
    @XmlElement(name = "F_CDTR_SHORT_NAME")
    protected String fcdtrshortname;
    @XmlElement(name = "F_CDT_CUST_SEGMENT")
    protected String fcdtcustsegment;
    @XmlElement(name = "F_CDT_CUST_FEE_ACCOUNT_OFFICE")
    protected String fcdtcustfeeaccountoffice;
    @XmlElement(name = "F_CDT_CUST_FEE_ACCOUNT_CCY")
    protected String fcdtcustfeeaccountccy;
    @XmlElement(name = "F_CDT_CUST_ABA")
    protected String fcdtcustaba;
    @XmlElement(name = "F_CDT_CUST_BASE_NO")
    protected String fcdtcustbaseno;
    @XmlElement(name = "F_CDT_CUST_CLEARING_CODE")
    protected String fcdtcustclearingcode;
    @XmlElement(name = "F_CDT_CUST_COUNTRYCODE")
    protected String fcdtcustcountrycode;
    @XmlElement(name = "F_CDT_CUST_CUST_CATEGORY")
    protected String fcdtcustcustcategory;
    @XmlElement(name = "F_CDT_CUST_CUST_CODE")
    protected String fcdtcustcustcode;
    @XmlElement(name = "F_CDT_CUST_CUST_NAME")
    protected String fcdtcustcustname;
    @XmlElement(name = "F_CDT_CUST_CUST_TYPE")
    protected String fcdtcustcusttype;
    @XmlElement(name = "F_CDT_CUST_DEPARTMENT")
    protected String fcdtcustdepartment;
    @XmlElement(name = "F_CDT_CUST_FEE_ACCOUNT_NO")
    protected String fcdtcustfeeaccountno;
    @XmlElement(name = "F_CDT_CUST_FROMREASON")
    protected String fcdtcustfromreason;
    @XmlElement(name = "F_CDT_CUST_IBAN_BANK_ID")
    protected String fcdtcustibanbankid;
    @XmlElement(name = "F_CDT_CUST_OWNERSHIP")
    protected String fcdtcustownership;
    @XmlElement(name = "F_CDT_CUST_RESIDENCY1")
    protected String fcdtcustresidency1;
    @XmlElement(name = "F_CDT_CUST_PROFESSION")
    protected String fcdtcustprofession;
    @XmlElement(name = "F_CDT_CUST_REG_REPORT1")
    protected String fcdtcustregreport1;
    @XmlElement(name = "F_CDT_CUST_REG_REPORT2")
    protected String fcdtcustregreport2;
    @XmlElement(name = "F_CDT_CUST_ALIAS")
    protected String fcdtcustalias;
    @XmlElement(name = "F_CDT_CUST_STOPFLAGFROM", defaultValue = "0")
    protected Integer fcdtcuststopflagfrom;
    @XmlElement(name = "F_CDT_CUST_STOPFLAGTO", defaultValue = "0")
    protected Integer fcdtcuststopflagto;
    @XmlElement(name = "F_CDT_CUST_SWIFT_ID")
    protected String fcdtcustswiftid;
    @XmlElement(name = "F_CDT_CUST_TOREASON")
    protected String fcdtcusttoreason;
    @XmlElement(name = "F_CDT_CUST_STATE")
    protected String fcdtcuststate;
    @XmlElement(name = "F_CDT_CUST_CITY")
    protected String fcdtcustcity;
    @XmlElement(name = "F_CDT_CUST_ZIP")
    protected String fcdtcustzip;
    @XmlElement(name = "F_CDT_CUST_ADDRESS1")
    protected String fcdtcustaddress1;
    @XmlElement(name = "F_CDT_CUST_ADDRESS2")
    protected String fcdtcustaddress2;
    @XmlElement(name = "F_CDT_CUST_ADDRESS3")
    protected String fcdtcustaddress3;
    @XmlElement(name = "F_CDT_CUST_ADDRESS4")
    protected String fcdtcustaddress4;
    @XmlElement(name = "F_CDT_CUST_ADDRESS5")
    protected String fcdtcustaddress5;
    @XmlElement(name = "F_CDT_CUST_ADDRESS6")
    protected String fcdtcustaddress6;
    @XmlElement(name = "F_CDT_CUST_ADDRESS7")
    protected String fcdtcustaddress7;
    @XmlElement(name = "F_CDT_CUST_BUILDING_NAME")
    protected String fcdtcustbuildingname;
    @XmlElement(name = "F_CDT_CUST_BUILDING_ROOM_NUMBER")
    protected String fcdtcustbuildingroomnumber;
    @XmlElement(name = "F_CDT_CUST_BUILDING_FLOOR")
    protected String fcdtcustbuildingfloor;
    @XmlElement(name = "F_CDT_CUST_POST_OFFICE_BOX")
    protected String fcdtcustpostofficebox;
    @XmlElement(name = "F_CDT_CUST_TOWN_LOCATION_NAME")
    protected String fcdtcusttownlocationname;
    @XmlElement(name = "F_CDT_CUST_DISTRICT_NAME")
    protected String fcdtcustdistrictname;
    @XmlElement(name = "F_CDT_CUST_ADDRESS_TYPE")
    protected String fcdtcustaddresstype;
    @XmlElement(name = "F_CDT_CUST_PSTLADR_ADDRESS_TYPE_PRTRY_ID")
    protected String fcdtcustpstladraddresstypeprtryid;
    @XmlElement(name = "F_CDT_CUST_PSTLADR_ADDRESS_TYPE_PRTRY_ISSUER")
    protected String fcdtcustpstladraddresstypeprtryissuer;
    @XmlElement(name = "F_CDT_CUST_PSTLADR_ADDRESS_TYPE_PRTRY_SCHME_NM")
    protected String fcdtcustpstladraddresstypeprtryschmenm;
    @XmlElement(name = "F_CDT_CUST_STREET_NAME")
    protected String fcdtcuststreetname;
    @XmlElement(name = "F_CDT_CUST_BUILDING_NO")
    protected String fcdtcustbuildingno;
    @XmlElement(name = "F_CDT_CUST_DIVISION")
    protected String fcdtcustdivision;
    @XmlElement(name = "F_CDT_CUST_SUB_DIVISION")
    protected String fcdtcustsubdivision;
    @XmlElement(name = "F_CDT_CUST_COUNTRY_SUB_DIVISION")
    protected String fcdtcustcountrysubdivision;

    /**
     * Gets the value of the fcdtrfullname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTRFULLNAME() {
        return fcdtrfullname;
    }

    /**
     * Sets the value of the fcdtrfullname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTRFULLNAME(String value) {
        this.fcdtrfullname = value;
    }

    /**
     * Gets the value of the fcdtrshortname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTRSHORTNAME() {
        return fcdtrshortname;
    }

    /**
     * Sets the value of the fcdtrshortname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTRSHORTNAME(String value) {
        this.fcdtrshortname = value;
    }

    /**
     * Gets the value of the fcdtcustsegment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTSEGMENT() {
        return fcdtcustsegment;
    }

    /**
     * Sets the value of the fcdtcustsegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTSEGMENT(String value) {
        this.fcdtcustsegment = value;
    }

    /**
     * Gets the value of the fcdtcustfeeaccountoffice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTFEEACCOUNTOFFICE() {
        return fcdtcustfeeaccountoffice;
    }

    /**
     * Sets the value of the fcdtcustfeeaccountoffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTFEEACCOUNTOFFICE(String value) {
        this.fcdtcustfeeaccountoffice = value;
    }

    /**
     * Gets the value of the fcdtcustfeeaccountccy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTFEEACCOUNTCCY() {
        return fcdtcustfeeaccountccy;
    }

    /**
     * Sets the value of the fcdtcustfeeaccountccy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTFEEACCOUNTCCY(String value) {
        this.fcdtcustfeeaccountccy = value;
    }

    /**
     * Gets the value of the fcdtcustaba property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTABA() {
        return fcdtcustaba;
    }

    /**
     * Sets the value of the fcdtcustaba property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTABA(String value) {
        this.fcdtcustaba = value;
    }

    /**
     * Gets the value of the fcdtcustbaseno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTBASENO() {
        return fcdtcustbaseno;
    }

    /**
     * Sets the value of the fcdtcustbaseno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTBASENO(String value) {
        this.fcdtcustbaseno = value;
    }

    /**
     * Gets the value of the fcdtcustclearingcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTCLEARINGCODE() {
        return fcdtcustclearingcode;
    }

    /**
     * Sets the value of the fcdtcustclearingcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTCLEARINGCODE(String value) {
        this.fcdtcustclearingcode = value;
    }

    /**
     * Gets the value of the fcdtcustcountrycode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTCOUNTRYCODE() {
        return fcdtcustcountrycode;
    }

    /**
     * Sets the value of the fcdtcustcountrycode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTCOUNTRYCODE(String value) {
        this.fcdtcustcountrycode = value;
    }

    /**
     * Gets the value of the fcdtcustcustcategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTCUSTCATEGORY() {
        return fcdtcustcustcategory;
    }

    /**
     * Sets the value of the fcdtcustcustcategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTCUSTCATEGORY(String value) {
        this.fcdtcustcustcategory = value;
    }

    /**
     * Gets the value of the fcdtcustcustcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTCUSTCODE() {
        return fcdtcustcustcode;
    }

    /**
     * Sets the value of the fcdtcustcustcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTCUSTCODE(String value) {
        this.fcdtcustcustcode = value;
    }

    /**
     * Gets the value of the fcdtcustcustname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTCUSTNAME() {
        return fcdtcustcustname;
    }

    /**
     * Sets the value of the fcdtcustcustname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTCUSTNAME(String value) {
        this.fcdtcustcustname = value;
    }

    /**
     * Gets the value of the fcdtcustcusttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTCUSTTYPE() {
        return fcdtcustcusttype;
    }

    /**
     * Sets the value of the fcdtcustcusttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTCUSTTYPE(String value) {
        this.fcdtcustcusttype = value;
    }

    /**
     * Gets the value of the fcdtcustdepartment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTDEPARTMENT() {
        return fcdtcustdepartment;
    }

    /**
     * Sets the value of the fcdtcustdepartment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTDEPARTMENT(String value) {
        this.fcdtcustdepartment = value;
    }

    /**
     * Gets the value of the fcdtcustfeeaccountno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTFEEACCOUNTNO() {
        return fcdtcustfeeaccountno;
    }

    /**
     * Sets the value of the fcdtcustfeeaccountno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTFEEACCOUNTNO(String value) {
        this.fcdtcustfeeaccountno = value;
    }

    /**
     * Gets the value of the fcdtcustfromreason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTFROMREASON() {
        return fcdtcustfromreason;
    }

    /**
     * Sets the value of the fcdtcustfromreason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTFROMREASON(String value) {
        this.fcdtcustfromreason = value;
    }

    /**
     * Gets the value of the fcdtcustibanbankid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTIBANBANKID() {
        return fcdtcustibanbankid;
    }

    /**
     * Sets the value of the fcdtcustibanbankid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTIBANBANKID(String value) {
        this.fcdtcustibanbankid = value;
    }

    /**
     * Gets the value of the fcdtcustownership property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTOWNERSHIP() {
        return fcdtcustownership;
    }

    /**
     * Sets the value of the fcdtcustownership property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTOWNERSHIP(String value) {
        this.fcdtcustownership = value;
    }

    /**
     * Gets the value of the fcdtcustresidency1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTRESIDENCY1() {
        return fcdtcustresidency1;
    }

    /**
     * Sets the value of the fcdtcustresidency1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTRESIDENCY1(String value) {
        this.fcdtcustresidency1 = value;
    }

    /**
     * Gets the value of the fcdtcustprofession property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTPROFESSION() {
        return fcdtcustprofession;
    }

    /**
     * Sets the value of the fcdtcustprofession property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTPROFESSION(String value) {
        this.fcdtcustprofession = value;
    }

    /**
     * Gets the value of the fcdtcustregreport1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTREGREPORT1() {
        return fcdtcustregreport1;
    }

    /**
     * Sets the value of the fcdtcustregreport1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTREGREPORT1(String value) {
        this.fcdtcustregreport1 = value;
    }

    /**
     * Gets the value of the fcdtcustregreport2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTREGREPORT2() {
        return fcdtcustregreport2;
    }

    /**
     * Sets the value of the fcdtcustregreport2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTREGREPORT2(String value) {
        this.fcdtcustregreport2 = value;
    }

    /**
     * Gets the value of the fcdtcustalias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTALIAS() {
        return fcdtcustalias;
    }

    /**
     * Sets the value of the fcdtcustalias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTALIAS(String value) {
        this.fcdtcustalias = value;
    }

    /**
     * Gets the value of the fcdtcuststopflagfrom property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFCDTCUSTSTOPFLAGFROM() {
        return fcdtcuststopflagfrom;
    }

    /**
     * Sets the value of the fcdtcuststopflagfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFCDTCUSTSTOPFLAGFROM(Integer value) {
        this.fcdtcuststopflagfrom = value;
    }

    /**
     * Gets the value of the fcdtcuststopflagto property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFCDTCUSTSTOPFLAGTO() {
        return fcdtcuststopflagto;
    }

    /**
     * Sets the value of the fcdtcuststopflagto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFCDTCUSTSTOPFLAGTO(Integer value) {
        this.fcdtcuststopflagto = value;
    }

    /**
     * Gets the value of the fcdtcustswiftid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTSWIFTID() {
        return fcdtcustswiftid;
    }

    /**
     * Sets the value of the fcdtcustswiftid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTSWIFTID(String value) {
        this.fcdtcustswiftid = value;
    }

    /**
     * Gets the value of the fcdtcusttoreason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTTOREASON() {
        return fcdtcusttoreason;
    }

    /**
     * Sets the value of the fcdtcusttoreason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTTOREASON(String value) {
        this.fcdtcusttoreason = value;
    }

    /**
     * Gets the value of the fcdtcuststate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTSTATE() {
        return fcdtcuststate;
    }

    /**
     * Sets the value of the fcdtcuststate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTSTATE(String value) {
        this.fcdtcuststate = value;
    }

    /**
     * Gets the value of the fcdtcustcity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTCITY() {
        return fcdtcustcity;
    }

    /**
     * Sets the value of the fcdtcustcity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTCITY(String value) {
        this.fcdtcustcity = value;
    }

    /**
     * Gets the value of the fcdtcustzip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTZIP() {
        return fcdtcustzip;
    }

    /**
     * Sets the value of the fcdtcustzip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTZIP(String value) {
        this.fcdtcustzip = value;
    }

    /**
     * Gets the value of the fcdtcustaddress1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTADDRESS1() {
        return fcdtcustaddress1;
    }

    /**
     * Sets the value of the fcdtcustaddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTADDRESS1(String value) {
        this.fcdtcustaddress1 = value;
    }

    /**
     * Gets the value of the fcdtcustaddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTADDRESS2() {
        return fcdtcustaddress2;
    }

    /**
     * Sets the value of the fcdtcustaddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTADDRESS2(String value) {
        this.fcdtcustaddress2 = value;
    }

    /**
     * Gets the value of the fcdtcustaddress3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTADDRESS3() {
        return fcdtcustaddress3;
    }

    /**
     * Sets the value of the fcdtcustaddress3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTADDRESS3(String value) {
        this.fcdtcustaddress3 = value;
    }

    /**
     * Gets the value of the fcdtcustaddress4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTADDRESS4() {
        return fcdtcustaddress4;
    }

    /**
     * Sets the value of the fcdtcustaddress4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTADDRESS4(String value) {
        this.fcdtcustaddress4 = value;
    }

    /**
     * Gets the value of the fcdtcustaddress5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTADDRESS5() {
        return fcdtcustaddress5;
    }

    /**
     * Sets the value of the fcdtcustaddress5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTADDRESS5(String value) {
        this.fcdtcustaddress5 = value;
    }

    /**
     * Gets the value of the fcdtcustaddress6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTADDRESS6() {
        return fcdtcustaddress6;
    }

    /**
     * Sets the value of the fcdtcustaddress6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTADDRESS6(String value) {
        this.fcdtcustaddress6 = value;
    }

    /**
     * Gets the value of the fcdtcustaddress7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTADDRESS7() {
        return fcdtcustaddress7;
    }

    /**
     * Sets the value of the fcdtcustaddress7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTADDRESS7(String value) {
        this.fcdtcustaddress7 = value;
    }

    /**
     * Gets the value of the fcdtcustbuildingname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTBUILDINGNAME() {
        return fcdtcustbuildingname;
    }

    /**
     * Sets the value of the fcdtcustbuildingname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTBUILDINGNAME(String value) {
        this.fcdtcustbuildingname = value;
    }

    /**
     * Gets the value of the fcdtcustbuildingroomnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTBUILDINGROOMNUMBER() {
        return fcdtcustbuildingroomnumber;
    }

    /**
     * Sets the value of the fcdtcustbuildingroomnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTBUILDINGROOMNUMBER(String value) {
        this.fcdtcustbuildingroomnumber = value;
    }

    /**
     * Gets the value of the fcdtcustbuildingfloor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTBUILDINGFLOOR() {
        return fcdtcustbuildingfloor;
    }

    /**
     * Sets the value of the fcdtcustbuildingfloor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTBUILDINGFLOOR(String value) {
        this.fcdtcustbuildingfloor = value;
    }

    /**
     * Gets the value of the fcdtcustpostofficebox property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTPOSTOFFICEBOX() {
        return fcdtcustpostofficebox;
    }

    /**
     * Sets the value of the fcdtcustpostofficebox property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTPOSTOFFICEBOX(String value) {
        this.fcdtcustpostofficebox = value;
    }

    /**
     * Gets the value of the fcdtcusttownlocationname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTTOWNLOCATIONNAME() {
        return fcdtcusttownlocationname;
    }

    /**
     * Sets the value of the fcdtcusttownlocationname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTTOWNLOCATIONNAME(String value) {
        this.fcdtcusttownlocationname = value;
    }

    /**
     * Gets the value of the fcdtcustdistrictname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTDISTRICTNAME() {
        return fcdtcustdistrictname;
    }

    /**
     * Sets the value of the fcdtcustdistrictname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTDISTRICTNAME(String value) {
        this.fcdtcustdistrictname = value;
    }

    /**
     * Gets the value of the fcdtcustaddresstype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTADDRESSTYPE() {
        return fcdtcustaddresstype;
    }

    /**
     * Sets the value of the fcdtcustaddresstype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTADDRESSTYPE(String value) {
        this.fcdtcustaddresstype = value;
    }

    /**
     * Gets the value of the fcdtcustpstladraddresstypeprtryid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTPSTLADRADDRESSTYPEPRTRYID() {
        return fcdtcustpstladraddresstypeprtryid;
    }

    /**
     * Sets the value of the fcdtcustpstladraddresstypeprtryid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTPSTLADRADDRESSTYPEPRTRYID(String value) {
        this.fcdtcustpstladraddresstypeprtryid = value;
    }

    /**
     * Gets the value of the fcdtcustpstladraddresstypeprtryissuer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTPSTLADRADDRESSTYPEPRTRYISSUER() {
        return fcdtcustpstladraddresstypeprtryissuer;
    }

    /**
     * Sets the value of the fcdtcustpstladraddresstypeprtryissuer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTPSTLADRADDRESSTYPEPRTRYISSUER(String value) {
        this.fcdtcustpstladraddresstypeprtryissuer = value;
    }

    /**
     * Gets the value of the fcdtcustpstladraddresstypeprtryschmenm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTPSTLADRADDRESSTYPEPRTRYSCHMENM() {
        return fcdtcustpstladraddresstypeprtryschmenm;
    }

    /**
     * Sets the value of the fcdtcustpstladraddresstypeprtryschmenm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTPSTLADRADDRESSTYPEPRTRYSCHMENM(String value) {
        this.fcdtcustpstladraddresstypeprtryschmenm = value;
    }

    /**
     * Gets the value of the fcdtcuststreetname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTSTREETNAME() {
        return fcdtcuststreetname;
    }

    /**
     * Sets the value of the fcdtcuststreetname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTSTREETNAME(String value) {
        this.fcdtcuststreetname = value;
    }

    /**
     * Gets the value of the fcdtcustbuildingno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTBUILDINGNO() {
        return fcdtcustbuildingno;
    }

    /**
     * Sets the value of the fcdtcustbuildingno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTBUILDINGNO(String value) {
        this.fcdtcustbuildingno = value;
    }

    /**
     * Gets the value of the fcdtcustdivision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTDIVISION() {
        return fcdtcustdivision;
    }

    /**
     * Sets the value of the fcdtcustdivision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTDIVISION(String value) {
        this.fcdtcustdivision = value;
    }

    /**
     * Gets the value of the fcdtcustsubdivision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTSUBDIVISION() {
        return fcdtcustsubdivision;
    }

    /**
     * Sets the value of the fcdtcustsubdivision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTSUBDIVISION(String value) {
        this.fcdtcustsubdivision = value;
    }

    /**
     * Gets the value of the fcdtcustcountrysubdivision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCUSTCOUNTRYSUBDIVISION() {
        return fcdtcustcountrysubdivision;
    }

    /**
     * Sets the value of the fcdtcustcountrysubdivision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCUSTCOUNTRYSUBDIVISION(String value) {
        this.fcdtcustcountrysubdivision = value;
    }

}
