//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.02 at 08:50:07 PM CEST 
//


package org.example.model.fin.com.fundtech.scl.commontypes;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for M_CDT_ACCOUNTType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="M_CDT_ACCOUNTType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="F_CDT_ACCT_AKA_ACC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_ACCT_STATUS_AT_BK_SYS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_ACCT_PROD_CD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_ACCT_ACCOUNTNAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_ACCT_EXT_ACCT_IND" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_ACCT_ASSET" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_REL_ACCT_OFFICE" type="{http://fundtech.com/SCL/CommonTypes}OfficeType" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_REL_ACCT_NB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_REL_ACCT_CCY" type="{http://fundtech.com/SCL/CommonTypes}CurrencyType" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_ACCT_STOPFLAGDR" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_ACCT_REASONDR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_ACCT_STOPFLAGCR" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_ACCT_REASONCR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_ACCT_BOOKNG_ENT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_ACCT_ACC_TYPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_ACCT_IS_RESIDENT" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_COST_CTR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_ACCT_IBAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_ACCT_FEE_ACCOUNT_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_ACCT_FEE_ACCOUNT_CCY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_ACCT_FEE_ACCOUNT_OFFICE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_ACCT_CREDIT_CONVERSION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_ACCT_DEBIT_CONVERSION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_ACCOUNTS_CTCT_NM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_ACCT_SERVICE_INSTITUTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_CDT_ACCT_BRNCHCD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "M_CDT_ACCOUNTType", propOrder = {

})
public class MCDTACCOUNTType {

    @XmlElement(name = "F_CDT_ACCT_AKA_ACC")
    protected String fcdtacctakaacc;
    @XmlElement(name = "F_CDT_ACCT_STATUS_AT_BK_SYS")
    protected String fcdtacctstatusatbksys;
    @XmlElement(name = "F_CDT_ACCT_PROD_CD")
    protected String fcdtacctprodcd;
    @XmlElement(name = "F_CDT_ACCT_ACCOUNTNAME")
    protected String fcdtacctaccountname;
    @XmlElement(name = "F_CDT_ACCT_EXT_ACCT_IND", defaultValue = "0")
    protected Integer fcdtacctextacctind;
    @XmlElement(name = "F_CDT_ACCT_ASSET")
    protected Boolean fcdtacctasset;
    @XmlElement(name = "F_CDT_REL_ACCT_OFFICE")
    protected String fcdtrelacctoffice;
    @XmlElement(name = "F_CDT_REL_ACCT_NB")
    protected String fcdtrelacctnb;
    @XmlElement(name = "F_CDT_REL_ACCT_CCY")
    protected String fcdtrelacctccy;
    @XmlElement(name = "F_CDT_ACCT_STOPFLAGDR", defaultValue = "0")
    protected Integer fcdtacctstopflagdr;
    @XmlElement(name = "F_CDT_ACCT_REASONDR")
    protected String fcdtacctreasondr;
    @XmlElement(name = "F_CDT_ACCT_STOPFLAGCR", defaultValue = "0")
    protected Integer fcdtacctstopflagcr;
    @XmlElement(name = "F_CDT_ACCT_REASONCR")
    protected String fcdtacctreasoncr;
    @XmlElement(name = "F_CDT_ACCT_BOOKNG_ENT")
    protected String fcdtacctbookngent;
    @XmlElement(name = "F_CDT_ACCT_ACC_TYPE")
    protected String fcdtacctacctype;
    @XmlElement(name = "F_CDT_ACCT_IS_RESIDENT", defaultValue = "0")
    protected Integer fcdtacctisresident;
    @XmlElement(name = "F_CDT_COST_CTR")
    protected String fcdtcostctr;
    @XmlElement(name = "F_CDT_ACCT_IBAN")
    protected String fcdtacctiban;
    @XmlElement(name = "F_CDT_ACCT_FEE_ACCOUNT_NO")
    protected String fcdtacctfeeaccountno;
    @XmlElement(name = "F_CDT_ACCT_FEE_ACCOUNT_CCY")
    protected String fcdtacctfeeaccountccy;
    @XmlElement(name = "F_CDT_ACCT_FEE_ACCOUNT_OFFICE")
    protected String fcdtacctfeeaccountoffice;
    @XmlElement(name = "F_CDT_ACCT_CREDIT_CONVERSION")
    protected String fcdtacctcreditconversion;
    @XmlElement(name = "F_CDT_ACCT_DEBIT_CONVERSION")
    protected String fcdtacctdebitconversion;
    @XmlElement(name = "F_ACCOUNTS_CTCT_NM")
    protected String faccountsctctnm;
    @XmlElement(name = "F_CDT_ACCT_SERVICE_INSTITUTION")
    protected String fcdtacctserviceinstitution;
    @XmlElement(name = "F_CDT_ACCT_BRNCHCD")
    protected String fcdtacctbrnchcd;

    /**
     * Gets the value of the fcdtacctakaacc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTACCTAKAACC() {
        return fcdtacctakaacc;
    }

    /**
     * Sets the value of the fcdtacctakaacc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTACCTAKAACC(String value) {
        this.fcdtacctakaacc = value;
    }

    /**
     * Gets the value of the fcdtacctstatusatbksys property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTACCTSTATUSATBKSYS() {
        return fcdtacctstatusatbksys;
    }

    /**
     * Sets the value of the fcdtacctstatusatbksys property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTACCTSTATUSATBKSYS(String value) {
        this.fcdtacctstatusatbksys = value;
    }

    /**
     * Gets the value of the fcdtacctprodcd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTACCTPRODCD() {
        return fcdtacctprodcd;
    }

    /**
     * Sets the value of the fcdtacctprodcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTACCTPRODCD(String value) {
        this.fcdtacctprodcd = value;
    }

    /**
     * Gets the value of the fcdtacctaccountname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTACCTACCOUNTNAME() {
        return fcdtacctaccountname;
    }

    /**
     * Sets the value of the fcdtacctaccountname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTACCTACCOUNTNAME(String value) {
        this.fcdtacctaccountname = value;
    }

    /**
     * Gets the value of the fcdtacctextacctind property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFCDTACCTEXTACCTIND() {
        return fcdtacctextacctind;
    }

    /**
     * Sets the value of the fcdtacctextacctind property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFCDTACCTEXTACCTIND(Integer value) {
        this.fcdtacctextacctind = value;
    }

    /**
     * Gets the value of the fcdtacctasset property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFCDTACCTASSET() {
        return fcdtacctasset;
    }

    /**
     * Sets the value of the fcdtacctasset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFCDTACCTASSET(Boolean value) {
        this.fcdtacctasset = value;
    }

    /**
     * Gets the value of the fcdtrelacctoffice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTRELACCTOFFICE() {
        return fcdtrelacctoffice;
    }

    /**
     * Sets the value of the fcdtrelacctoffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTRELACCTOFFICE(String value) {
        this.fcdtrelacctoffice = value;
    }

    /**
     * Gets the value of the fcdtrelacctnb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTRELACCTNB() {
        return fcdtrelacctnb;
    }

    /**
     * Sets the value of the fcdtrelacctnb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTRELACCTNB(String value) {
        this.fcdtrelacctnb = value;
    }

    /**
     * Gets the value of the fcdtrelacctccy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTRELACCTCCY() {
        return fcdtrelacctccy;
    }

    /**
     * Sets the value of the fcdtrelacctccy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTRELACCTCCY(String value) {
        this.fcdtrelacctccy = value;
    }

    /**
     * Gets the value of the fcdtacctstopflagdr property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFCDTACCTSTOPFLAGDR() {
        return fcdtacctstopflagdr;
    }

    /**
     * Sets the value of the fcdtacctstopflagdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFCDTACCTSTOPFLAGDR(Integer value) {
        this.fcdtacctstopflagdr = value;
    }

    /**
     * Gets the value of the fcdtacctreasondr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTACCTREASONDR() {
        return fcdtacctreasondr;
    }

    /**
     * Sets the value of the fcdtacctreasondr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTACCTREASONDR(String value) {
        this.fcdtacctreasondr = value;
    }

    /**
     * Gets the value of the fcdtacctstopflagcr property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFCDTACCTSTOPFLAGCR() {
        return fcdtacctstopflagcr;
    }

    /**
     * Sets the value of the fcdtacctstopflagcr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFCDTACCTSTOPFLAGCR(Integer value) {
        this.fcdtacctstopflagcr = value;
    }

    /**
     * Gets the value of the fcdtacctreasoncr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTACCTREASONCR() {
        return fcdtacctreasoncr;
    }

    /**
     * Sets the value of the fcdtacctreasoncr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTACCTREASONCR(String value) {
        this.fcdtacctreasoncr = value;
    }

    /**
     * Gets the value of the fcdtacctbookngent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTACCTBOOKNGENT() {
        return fcdtacctbookngent;
    }

    /**
     * Sets the value of the fcdtacctbookngent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTACCTBOOKNGENT(String value) {
        this.fcdtacctbookngent = value;
    }

    /**
     * Gets the value of the fcdtacctacctype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTACCTACCTYPE() {
        return fcdtacctacctype;
    }

    /**
     * Sets the value of the fcdtacctacctype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTACCTACCTYPE(String value) {
        this.fcdtacctacctype = value;
    }

    /**
     * Gets the value of the fcdtacctisresident property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFCDTACCTISRESIDENT() {
        return fcdtacctisresident;
    }

    /**
     * Sets the value of the fcdtacctisresident property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFCDTACCTISRESIDENT(Integer value) {
        this.fcdtacctisresident = value;
    }

    /**
     * Gets the value of the fcdtcostctr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTCOSTCTR() {
        return fcdtcostctr;
    }

    /**
     * Sets the value of the fcdtcostctr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTCOSTCTR(String value) {
        this.fcdtcostctr = value;
    }

    /**
     * Gets the value of the fcdtacctiban property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTACCTIBAN() {
        return fcdtacctiban;
    }

    /**
     * Sets the value of the fcdtacctiban property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTACCTIBAN(String value) {
        this.fcdtacctiban = value;
    }

    /**
     * Gets the value of the fcdtacctfeeaccountno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTACCTFEEACCOUNTNO() {
        return fcdtacctfeeaccountno;
    }

    /**
     * Sets the value of the fcdtacctfeeaccountno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTACCTFEEACCOUNTNO(String value) {
        this.fcdtacctfeeaccountno = value;
    }

    /**
     * Gets the value of the fcdtacctfeeaccountccy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTACCTFEEACCOUNTCCY() {
        return fcdtacctfeeaccountccy;
    }

    /**
     * Sets the value of the fcdtacctfeeaccountccy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTACCTFEEACCOUNTCCY(String value) {
        this.fcdtacctfeeaccountccy = value;
    }

    /**
     * Gets the value of the fcdtacctfeeaccountoffice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTACCTFEEACCOUNTOFFICE() {
        return fcdtacctfeeaccountoffice;
    }

    /**
     * Sets the value of the fcdtacctfeeaccountoffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTACCTFEEACCOUNTOFFICE(String value) {
        this.fcdtacctfeeaccountoffice = value;
    }

    /**
     * Gets the value of the fcdtacctcreditconversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTACCTCREDITCONVERSION() {
        return fcdtacctcreditconversion;
    }

    /**
     * Sets the value of the fcdtacctcreditconversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTACCTCREDITCONVERSION(String value) {
        this.fcdtacctcreditconversion = value;
    }

    /**
     * Gets the value of the fcdtacctdebitconversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTACCTDEBITCONVERSION() {
        return fcdtacctdebitconversion;
    }

    /**
     * Sets the value of the fcdtacctdebitconversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTACCTDEBITCONVERSION(String value) {
        this.fcdtacctdebitconversion = value;
    }

    /**
     * Gets the value of the faccountsctctnm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFACCOUNTSCTCTNM() {
        return faccountsctctnm;
    }

    /**
     * Sets the value of the faccountsctctnm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFACCOUNTSCTCTNM(String value) {
        this.faccountsctctnm = value;
    }

    /**
     * Gets the value of the fcdtacctserviceinstitution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTACCTSERVICEINSTITUTION() {
        return fcdtacctserviceinstitution;
    }

    /**
     * Sets the value of the fcdtacctserviceinstitution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTACCTSERVICEINSTITUTION(String value) {
        this.fcdtacctserviceinstitution = value;
    }

    /**
     * Gets the value of the fcdtacctbrnchcd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCDTACCTBRNCHCD() {
        return fcdtacctbrnchcd;
    }

    /**
     * Sets the value of the fcdtacctbrnchcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCDTACCTBRNCHCD(String value) {
        this.fcdtacctbrnchcd = value;
    }

}
