//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.02 at 08:50:07 PM CEST 
//


package org.example.model.fin.com.fundtech.scl.commontypes;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MsgErrLineType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MsgErrLineType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="F_MSGERR_CODE" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="F_MSGERR_TIME_STAMP" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="F_MSGERR_SEVERITY" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="F_MSGERR_CREATE_DATE" type="{http://fundtech.com/SCL/CommonTypes}ISODateTime"/&gt;
 *         &lt;element name="F_MSGERR_TIME_ZONE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="F_MSGERR_FAULT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSGERR_PARAMS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSGERR_DISPLAY" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="F_MSGERR_FIELD_LOGICAL_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSGERR_EXT_ERROR_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSGERR_EXT_ERROR_CODE_SOURCE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSGERR_TARGET_ERROR_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSGERR_DESC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MsgErrLineType", propOrder = {
    "fmsgerrcode",
    "fmsgerrtimestamp",
    "fmsgerrseverity",
    "fmsgerrcreatedate",
    "fmsgerrtimezone",
    "fmsgerrfault",
    "fmsgerrparams",
    "fmsgerrdisplay",
    "fmsgerrfieldlogicalid",
    "fmsgerrexterrorcode",
    "fmsgerrexterrorcodesource",
    "fmsgerrtargeterrorcode",
    "fmsgerrdesc"
})
public class MsgErrLineType {

    @XmlElement(name = "F_MSGERR_CODE")
    protected int fmsgerrcode;
    @XmlElement(name = "F_MSGERR_TIME_STAMP", required = true)
    protected String fmsgerrtimestamp;
    @XmlElement(name = "F_MSGERR_SEVERITY")
    protected Integer fmsgerrseverity;
    @XmlElement(name = "F_MSGERR_CREATE_DATE", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fmsgerrcreatedate;
    @XmlElement(name = "F_MSGERR_TIME_ZONE", required = true)
    protected String fmsgerrtimezone;
    @XmlElement(name = "F_MSGERR_FAULT")
    protected String fmsgerrfault;
    @XmlElement(name = "F_MSGERR_PARAMS")
    protected String fmsgerrparams;
    @XmlElement(name = "F_MSGERR_DISPLAY")
    protected Integer fmsgerrdisplay;
    @XmlElement(name = "F_MSGERR_FIELD_LOGICAL_ID")
    protected String fmsgerrfieldlogicalid;
    @XmlElement(name = "F_MSGERR_EXT_ERROR_CODE")
    protected String fmsgerrexterrorcode;
    @XmlElement(name = "F_MSGERR_EXT_ERROR_CODE_SOURCE")
    protected String fmsgerrexterrorcodesource;
    @XmlElement(name = "F_MSGERR_TARGET_ERROR_CODE")
    protected String fmsgerrtargeterrorcode;
    @XmlElement(name = "F_MSGERR_DESC")
    protected String fmsgerrdesc;

    /**
     * Gets the value of the fmsgerrcode property.
     * 
     */
    public int getFMSGERRCODE() {
        return fmsgerrcode;
    }

    /**
     * Sets the value of the fmsgerrcode property.
     * 
     */
    public void setFMSGERRCODE(int value) {
        this.fmsgerrcode = value;
    }

    /**
     * Gets the value of the fmsgerrtimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGERRTIMESTAMP() {
        return fmsgerrtimestamp;
    }

    /**
     * Sets the value of the fmsgerrtimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGERRTIMESTAMP(String value) {
        this.fmsgerrtimestamp = value;
    }

    /**
     * Gets the value of the fmsgerrseverity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFMSGERRSEVERITY() {
        return fmsgerrseverity;
    }

    /**
     * Sets the value of the fmsgerrseverity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFMSGERRSEVERITY(Integer value) {
        this.fmsgerrseverity = value;
    }

    /**
     * Gets the value of the fmsgerrcreatedate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFMSGERRCREATEDATE() {
        return fmsgerrcreatedate;
    }

    /**
     * Sets the value of the fmsgerrcreatedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFMSGERRCREATEDATE(XMLGregorianCalendar value) {
        this.fmsgerrcreatedate = value;
    }

    /**
     * Gets the value of the fmsgerrtimezone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGERRTIMEZONE() {
        return fmsgerrtimezone;
    }

    /**
     * Sets the value of the fmsgerrtimezone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGERRTIMEZONE(String value) {
        this.fmsgerrtimezone = value;
    }

    /**
     * Gets the value of the fmsgerrfault property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGERRFAULT() {
        return fmsgerrfault;
    }

    /**
     * Sets the value of the fmsgerrfault property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGERRFAULT(String value) {
        this.fmsgerrfault = value;
    }

    /**
     * Gets the value of the fmsgerrparams property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGERRPARAMS() {
        return fmsgerrparams;
    }

    /**
     * Sets the value of the fmsgerrparams property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGERRPARAMS(String value) {
        this.fmsgerrparams = value;
    }

    /**
     * Gets the value of the fmsgerrdisplay property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFMSGERRDISPLAY() {
        return fmsgerrdisplay;
    }

    /**
     * Sets the value of the fmsgerrdisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFMSGERRDISPLAY(Integer value) {
        this.fmsgerrdisplay = value;
    }

    /**
     * Gets the value of the fmsgerrfieldlogicalid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGERRFIELDLOGICALID() {
        return fmsgerrfieldlogicalid;
    }

    /**
     * Sets the value of the fmsgerrfieldlogicalid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGERRFIELDLOGICALID(String value) {
        this.fmsgerrfieldlogicalid = value;
    }

    /**
     * Gets the value of the fmsgerrexterrorcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGERREXTERRORCODE() {
        return fmsgerrexterrorcode;
    }

    /**
     * Sets the value of the fmsgerrexterrorcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGERREXTERRORCODE(String value) {
        this.fmsgerrexterrorcode = value;
    }

    /**
     * Gets the value of the fmsgerrexterrorcodesource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGERREXTERRORCODESOURCE() {
        return fmsgerrexterrorcodesource;
    }

    /**
     * Sets the value of the fmsgerrexterrorcodesource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGERREXTERRORCODESOURCE(String value) {
        this.fmsgerrexterrorcodesource = value;
    }

    /**
     * Gets the value of the fmsgerrtargeterrorcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGERRTARGETERRORCODE() {
        return fmsgerrtargeterrorcode;
    }

    /**
     * Sets the value of the fmsgerrtargeterrorcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGERRTARGETERRORCODE(String value) {
        this.fmsgerrtargeterrorcode = value;
    }

    /**
     * Gets the value of the fmsgerrdesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGERRDESC() {
        return fmsgerrdesc;
    }

    /**
     * Sets the value of the fmsgerrdesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGERRDESC(String value) {
        this.fmsgerrdesc = value;
    }

}
