//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.31 at 09:11:08 PM CEST 
//


package org.example.model.fin.com.fundtech.scl.commontypes;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 *         map("ERROR_CODE", "F_SI_ERROR_CODE");
 *         map("ERROR_PARAMS", "F_SI_ERROR_PARAMS");
 *         map("SI_STATUS", "F_SI_STATUS");
 *         map("PARTY_TYPE", "F_SI_PARTY_TYPE");
 *         map("OBJECT_ID", "F_SI_OBJECT_ID");
 *         map("CREATE_DATE", "F_SI_CREATE_DT");
 *         map("ZONE_CODE", "F_SI_ZONE_CODE");
 *         map("TIME_STAMP", "F_SI_TIME_STAMP");
 *         map("PREVENT_STP_UID", "F_SI_PREVENT_STP_UID");
 *         map("USER_ID", "F_SI_USER_ID");
 *       
 * 
 * <p>Java class for MsgSpecialInstructionsLine complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MsgSpecialInstructionsLine"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="F_SI_ERROR_CODE" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="F_SI_ERROR_PARAMS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="F_SI_STATUS" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="F_SI_PARTY_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="F_SI_OBJECT_ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="F_SI_CREATE_DT" type="{http://fundtech.com/SCL/CommonTypes}ISODateTime"/&gt;
 *         &lt;element name="F_SI_ZONE_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="F_SI_TIME_STAMP" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="F_SI_PREVENT_STP_UID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="F_SI_USER_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MsgSpecialInstructionsLine", propOrder = {

})
public class MsgSpecialInstructionsLine {

    @XmlElement(name = "F_SI_ERROR_CODE")
    protected int fsierrorcode;
    @XmlElement(name = "F_SI_ERROR_PARAMS", required = true)
    protected String fsierrorparams;
    @XmlElement(name = "F_SI_STATUS")
    protected int fsistatus;
    @XmlElement(name = "F_SI_PARTY_TYPE", required = true)
    protected String fsipartytype;
    @XmlElement(name = "F_SI_OBJECT_ID", required = true)
    protected String fsiobjectid;
    @XmlElement(name = "F_SI_CREATE_DT", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fsicreatedt;
    @XmlElement(name = "F_SI_ZONE_CODE", required = true)
    protected String fsizonecode;
    @XmlElement(name = "F_SI_TIME_STAMP", required = true)
    protected String fsitimestamp;
    @XmlElement(name = "F_SI_PREVENT_STP_UID", required = true)
    protected String fsipreventstpuid;
    @XmlElement(name = "F_SI_USER_ID")
    protected String fsiuserid;

    /**
     * Gets the value of the fsierrorcode property.
     * 
     */
    public int getFSIERRORCODE() {
        return fsierrorcode;
    }

    /**
     * Sets the value of the fsierrorcode property.
     * 
     */
    public void setFSIERRORCODE(int value) {
        this.fsierrorcode = value;
    }

    /**
     * Gets the value of the fsierrorparams property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFSIERRORPARAMS() {
        return fsierrorparams;
    }

    /**
     * Sets the value of the fsierrorparams property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFSIERRORPARAMS(String value) {
        this.fsierrorparams = value;
    }

    /**
     * Gets the value of the fsistatus property.
     * 
     */
    public int getFSISTATUS() {
        return fsistatus;
    }

    /**
     * Sets the value of the fsistatus property.
     * 
     */
    public void setFSISTATUS(int value) {
        this.fsistatus = value;
    }

    /**
     * Gets the value of the fsipartytype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFSIPARTYTYPE() {
        return fsipartytype;
    }

    /**
     * Sets the value of the fsipartytype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFSIPARTYTYPE(String value) {
        this.fsipartytype = value;
    }

    /**
     * Gets the value of the fsiobjectid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFSIOBJECTID() {
        return fsiobjectid;
    }

    /**
     * Sets the value of the fsiobjectid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFSIOBJECTID(String value) {
        this.fsiobjectid = value;
    }

    /**
     * Gets the value of the fsicreatedt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFSICREATEDT() {
        return fsicreatedt;
    }

    /**
     * Sets the value of the fsicreatedt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFSICREATEDT(XMLGregorianCalendar value) {
        this.fsicreatedt = value;
    }

    /**
     * Gets the value of the fsizonecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFSIZONECODE() {
        return fsizonecode;
    }

    /**
     * Sets the value of the fsizonecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFSIZONECODE(String value) {
        this.fsizonecode = value;
    }

    /**
     * Gets the value of the fsitimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFSITIMESTAMP() {
        return fsitimestamp;
    }

    /**
     * Sets the value of the fsitimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFSITIMESTAMP(String value) {
        this.fsitimestamp = value;
    }

    /**
     * Gets the value of the fsipreventstpuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFSIPREVENTSTPUID() {
        return fsipreventstpuid;
    }

    /**
     * Sets the value of the fsipreventstpuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFSIPREVENTSTPUID(String value) {
        this.fsipreventstpuid = value;
    }

    /**
     * Gets the value of the fsiuserid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFSIUSERID() {
        return fsiuserid;
    }

    /**
     * Sets the value of the fsiuserid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFSIUSERID(String value) {
        this.fsiuserid = value;
    }

}
