//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.02 at 08:50:07 PM CEST 
//


package org.example.model.fin.com.fundtech.scl.commontypes;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MsgType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MsgType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Pmnt" type="{http://fundtech.com/SCL/CommonTypes}PmntType" minOccurs="0"/&gt;
 *         &lt;element name="Extn" type="{http://fundtech.com/SCL/CommonTypes}FndtMsgExtensionType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MsgType", propOrder = {
    "pmnt",
    "extn"
})
public class MsgType {

    @XmlElement(name = "Pmnt")
    protected PmntType pmnt;
    @XmlElement(name = "Extn")
    protected FndtMsgExtensionType extn;

    /**
     * Gets the value of the pmnt property.
     * 
     * @return
     *     possible object is
     *     {@link PmntType }
     *     
     */
    public PmntType getPmnt() {
        return pmnt;
    }

    /**
     * Sets the value of the pmnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmntType }
     *     
     */
    public void setPmnt(PmntType value) {
        this.pmnt = value;
    }

    /**
     * Gets the value of the extn property.
     * 
     * @return
     *     possible object is
     *     {@link FndtMsgExtensionType }
     *     
     */
    public FndtMsgExtensionType getExtn() {
        return extn;
    }

    /**
     * Sets the value of the extn property.
     * 
     * @param value
     *     allowed object is
     *     {@link FndtMsgExtensionType }
     *     
     */
    public void setExtn(FndtMsgExtensionType value) {
        this.extn = value;
    }

}
