//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.31 at 09:11:08 PM CEST 
//


package org.example.model.fin.com.fundtech.scl.commontypes;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OperationalSectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OperationalSectionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="D_BUTTON_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="D_SCREENSET_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="D_PERFORMED_POSTING_ASAP" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="TemplateSection" type="{http://fundtech.com/SCL/CommonTypes}TemplateSectionType" minOccurs="0"/&gt;
 *         &lt;element name="RETURN_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RETURN_PRTRY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TRIGGERED_MSG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="GENERATED_MSG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ORIGINATED_BY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="D_PARENT_MID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="D_EXIT_POINT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="D_PARENT_IFID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="D_SEND_TO_REJECT_ACTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="D_REG_IND" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="D_ALL_ORCHESTRATION_GROUPS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="D_ORCHESTRATION_GROUP" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="D_ORCHESTRATION_STRUCTURE_WAS_CHANGED" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="D_NEW_ORCHESTRATION_GROUP_WAS_SENT" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="D_NEW_ORCHESTRATION_GROUPS_AFTER_REDO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="D_ORIG_BUTTON_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperationalSectionType", propOrder = {

})
public class OperationalSectionType {

    @XmlElement(name = "D_BUTTON_ID")
    protected String dbuttonid;
    @XmlElement(name = "D_SCREENSET_ID")
    protected String dscreensetid;
    @XmlElement(name = "D_PERFORMED_POSTING_ASAP")
    protected Boolean dperformedpostingasap;
    @XmlElement(name = "TemplateSection")
    protected TemplateSectionType templateSection;
    @XmlElement(name = "RETURN_CODE")
    protected String returncode;
    @XmlElement(name = "RETURN_PRTRY")
    protected String returnprtry;
    @XmlElement(name = "TRIGGERED_MSG")
    protected String triggeredmsg;
    @XmlElement(name = "GENERATED_MSG")
    protected String generatedmsg;
    @XmlElement(name = "ORIGINATED_BY")
    protected String originatedby;
    @XmlElement(name = "D_PARENT_MID")
    protected String dparentmid;
    @XmlElement(name = "D_EXIT_POINT")
    protected String dexitpoint;
    @XmlElement(name = "D_PARENT_IFID")
    protected String dparentifid;
    @XmlElement(name = "D_SEND_TO_REJECT_ACTION")
    protected String dsendtorejectaction;
    @XmlElement(name = "D_REG_IND")
    protected String dregind;
    @XmlElement(name = "D_ALL_ORCHESTRATION_GROUPS")
    protected String dallorchestrationgroups;
    @XmlElement(name = "D_ORCHESTRATION_GROUP")
    protected BigDecimal dorchestrationgroup;
    @XmlElement(name = "D_ORCHESTRATION_STRUCTURE_WAS_CHANGED")
    protected Boolean dorchestrationstructurewaschanged;
    @XmlElement(name = "D_NEW_ORCHESTRATION_GROUP_WAS_SENT")
    protected Boolean dneworchestrationgroupwassent;
    @XmlElement(name = "D_NEW_ORCHESTRATION_GROUPS_AFTER_REDO")
    protected String dneworchestrationgroupsafterredo;
    @XmlElement(name = "D_ORIG_BUTTON_ID")
    protected String dorigbuttonid;

    /**
     * Gets the value of the dbuttonid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDBUTTONID() {
        return dbuttonid;
    }

    /**
     * Sets the value of the dbuttonid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDBUTTONID(String value) {
        this.dbuttonid = value;
    }

    /**
     * Gets the value of the dscreensetid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDSCREENSETID() {
        return dscreensetid;
    }

    /**
     * Sets the value of the dscreensetid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDSCREENSETID(String value) {
        this.dscreensetid = value;
    }

    /**
     * Gets the value of the dperformedpostingasap property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDPERFORMEDPOSTINGASAP() {
        return dperformedpostingasap;
    }

    /**
     * Sets the value of the dperformedpostingasap property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDPERFORMEDPOSTINGASAP(Boolean value) {
        this.dperformedpostingasap = value;
    }

    /**
     * Gets the value of the templateSection property.
     * 
     * @return
     *     possible object is
     *     {@link TemplateSectionType }
     *     
     */
    public TemplateSectionType getTemplateSection() {
        return templateSection;
    }

    /**
     * Sets the value of the templateSection property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemplateSectionType }
     *     
     */
    public void setTemplateSection(TemplateSectionType value) {
        this.templateSection = value;
    }

    /**
     * Gets the value of the returncode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRETURNCODE() {
        return returncode;
    }

    /**
     * Sets the value of the returncode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRETURNCODE(String value) {
        this.returncode = value;
    }

    /**
     * Gets the value of the returnprtry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRETURNPRTRY() {
        return returnprtry;
    }

    /**
     * Sets the value of the returnprtry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRETURNPRTRY(String value) {
        this.returnprtry = value;
    }

    /**
     * Gets the value of the triggeredmsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRIGGEREDMSG() {
        return triggeredmsg;
    }

    /**
     * Sets the value of the triggeredmsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRIGGEREDMSG(String value) {
        this.triggeredmsg = value;
    }

    /**
     * Gets the value of the generatedmsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGENERATEDMSG() {
        return generatedmsg;
    }

    /**
     * Sets the value of the generatedmsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGENERATEDMSG(String value) {
        this.generatedmsg = value;
    }

    /**
     * Gets the value of the originatedby property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORIGINATEDBY() {
        return originatedby;
    }

    /**
     * Sets the value of the originatedby property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORIGINATEDBY(String value) {
        this.originatedby = value;
    }

    /**
     * Gets the value of the dparentmid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDPARENTMID() {
        return dparentmid;
    }

    /**
     * Sets the value of the dparentmid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDPARENTMID(String value) {
        this.dparentmid = value;
    }

    /**
     * Gets the value of the dexitpoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDEXITPOINT() {
        return dexitpoint;
    }

    /**
     * Sets the value of the dexitpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDEXITPOINT(String value) {
        this.dexitpoint = value;
    }

    /**
     * Gets the value of the dparentifid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDPARENTIFID() {
        return dparentifid;
    }

    /**
     * Sets the value of the dparentifid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDPARENTIFID(String value) {
        this.dparentifid = value;
    }

    /**
     * Gets the value of the dsendtorejectaction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDSENDTOREJECTACTION() {
        return dsendtorejectaction;
    }

    /**
     * Sets the value of the dsendtorejectaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDSENDTOREJECTACTION(String value) {
        this.dsendtorejectaction = value;
    }

    /**
     * Gets the value of the dregind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDREGIND() {
        return dregind;
    }

    /**
     * Sets the value of the dregind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDREGIND(String value) {
        this.dregind = value;
    }

    /**
     * Gets the value of the dallorchestrationgroups property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDALLORCHESTRATIONGROUPS() {
        return dallorchestrationgroups;
    }

    /**
     * Sets the value of the dallorchestrationgroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDALLORCHESTRATIONGROUPS(String value) {
        this.dallorchestrationgroups = value;
    }

    /**
     * Gets the value of the dorchestrationgroup property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDORCHESTRATIONGROUP() {
        return dorchestrationgroup;
    }

    /**
     * Sets the value of the dorchestrationgroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDORCHESTRATIONGROUP(BigDecimal value) {
        this.dorchestrationgroup = value;
    }

    /**
     * Gets the value of the dorchestrationstructurewaschanged property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDORCHESTRATIONSTRUCTUREWASCHANGED() {
        return dorchestrationstructurewaschanged;
    }

    /**
     * Sets the value of the dorchestrationstructurewaschanged property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDORCHESTRATIONSTRUCTUREWASCHANGED(Boolean value) {
        this.dorchestrationstructurewaschanged = value;
    }

    /**
     * Gets the value of the dneworchestrationgroupwassent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDNEWORCHESTRATIONGROUPWASSENT() {
        return dneworchestrationgroupwassent;
    }

    /**
     * Sets the value of the dneworchestrationgroupwassent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDNEWORCHESTRATIONGROUPWASSENT(Boolean value) {
        this.dneworchestrationgroupwassent = value;
    }

    /**
     * Gets the value of the dneworchestrationgroupsafterredo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDNEWORCHESTRATIONGROUPSAFTERREDO() {
        return dneworchestrationgroupsafterredo;
    }

    /**
     * Sets the value of the dneworchestrationgroupsafterredo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDNEWORCHESTRATIONGROUPSAFTERREDO(String value) {
        this.dneworchestrationgroupsafterredo = value;
    }

    /**
     * Gets the value of the dorigbuttonid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDORIGBUTTONID() {
        return dorigbuttonid;
    }

    /**
     * Sets the value of the dorigbuttonid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDORIGBUTTONID(String value) {
        this.dorigbuttonid = value;
    }

}
