//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.02 at 08:50:07 PM CEST 
//


package org.example.model.fin.com.fundtech.scl.commontypes;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TemplateSectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TemplateSectionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="D_TEMPLATE_UNCHANGED_FIELDS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="D_FULLY_TEMPLATE_FIELDS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TemplateSectionType", propOrder = {

})
public class TemplateSectionType {

    @XmlElement(name = "D_TEMPLATE_UNCHANGED_FIELDS")
    protected String dtemplateunchangedfields;
    @XmlElement(name = "D_FULLY_TEMPLATE_FIELDS")
    protected String dfullytemplatefields;

    /**
     * Gets the value of the dtemplateunchangedfields property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDTEMPLATEUNCHANGEDFIELDS() {
        return dtemplateunchangedfields;
    }

    /**
     * Sets the value of the dtemplateunchangedfields property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDTEMPLATEUNCHANGEDFIELDS(String value) {
        this.dtemplateunchangedfields = value;
    }

    /**
     * Gets the value of the dfullytemplatefields property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDFULLYTEMPLATEFIELDS() {
        return dfullytemplatefields;
    }

    /**
     * Sets the value of the dfullytemplatefields property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDFULLYTEMPLATEFIELDS(String value) {
        this.dfullytemplatefields = value;
    }

}
