//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.28 at 09:00:52 PM CEST 
//


package org.example.model.com.fundtech.scl.commontypes;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdvisingTypeLineType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdvisingTypeLineType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="F_ADVISING_UID_ADVISING" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="F_ADVISING_CONTACT_DETAILS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="F_ADVISING_CONTACT_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="F_ADVISING_CONTACT_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="F_ADVISING_MIN_AMT" type="{http://fundtech.com/SCL/CommonTypes}AmountType"/&gt;
 *         &lt;element name="F_ADVISING_ADVICE_SUB_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="F_ADVISING_ADVICE_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="F_ADVISING_FEE_ADVICE_IND" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="F_ADVISING_CR_ADVICE_IND" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="F_ADVISING_DR_ADVICE_IND" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="F_ADVISING_ADVICE_TO_PARTY" type="{http://fundtech.com/SCL/CommonTypes}AdviceToPartyType"/&gt;
 *         &lt;element name="F_ADVISING_ADVC_VEHICLE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="F_ADVISING_TEMP_ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="F_ADVISING_ACC_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdvisingTypeLineType", propOrder = {
    "fadvisinguidadvising",
    "fadvisingcontactdetails",
    "fadvisingcontacttype",
    "fadvisingcontactname",
    "fadvisingminamt",
    "fadvisingadvicesubtype",
    "fadvisingadvicetype",
    "fadvisingfeeadviceind",
    "fadvisingcradviceind",
    "fadvisingdradviceind",
    "fadvisingadvicetoparty",
    "fadvisingadvcvehicle",
    "fadvisingtempid",
    "fadvisingacctype"
})
public class AdvisingTypeLineType {

    @XmlElement(name = "F_ADVISING_UID_ADVISING", required = true)
    protected String fadvisinguidadvising;
    @XmlElement(name = "F_ADVISING_CONTACT_DETAILS", required = true)
    protected String fadvisingcontactdetails;
    @XmlElement(name = "F_ADVISING_CONTACT_TYPE", required = true)
    protected String fadvisingcontacttype;
    @XmlElement(name = "F_ADVISING_CONTACT_NAME", required = true)
    protected String fadvisingcontactname;
    @XmlElement(name = "F_ADVISING_MIN_AMT", required = true)
    protected BigDecimal fadvisingminamt;
    @XmlElement(name = "F_ADVISING_ADVICE_SUB_TYPE", required = true)
    protected String fadvisingadvicesubtype;
    @XmlElement(name = "F_ADVISING_ADVICE_TYPE", required = true)
    protected String fadvisingadvicetype;
    @XmlElement(name = "F_ADVISING_FEE_ADVICE_IND")
    protected boolean fadvisingfeeadviceind;
    @XmlElement(name = "F_ADVISING_CR_ADVICE_IND")
    protected boolean fadvisingcradviceind;
    @XmlElement(name = "F_ADVISING_DR_ADVICE_IND")
    protected boolean fadvisingdradviceind;
    @XmlElement(name = "F_ADVISING_ADVICE_TO_PARTY", required = true)
    @XmlSchemaType(name = "string")
    protected AdviceToPartyType fadvisingadvicetoparty;
    @XmlElement(name = "F_ADVISING_ADVC_VEHICLE", required = true)
    protected String fadvisingadvcvehicle;
    @XmlElement(name = "F_ADVISING_TEMP_ID", required = true)
    protected String fadvisingtempid;
    @XmlElement(name = "F_ADVISING_ACC_TYPE", required = true)
    protected String fadvisingacctype;

    /**
     * Gets the value of the fadvisinguidadvising property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFADVISINGUIDADVISING() {
        return fadvisinguidadvising;
    }

    /**
     * Sets the value of the fadvisinguidadvising property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFADVISINGUIDADVISING(String value) {
        this.fadvisinguidadvising = value;
    }

    /**
     * Gets the value of the fadvisingcontactdetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFADVISINGCONTACTDETAILS() {
        return fadvisingcontactdetails;
    }

    /**
     * Sets the value of the fadvisingcontactdetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFADVISINGCONTACTDETAILS(String value) {
        this.fadvisingcontactdetails = value;
    }

    /**
     * Gets the value of the fadvisingcontacttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFADVISINGCONTACTTYPE() {
        return fadvisingcontacttype;
    }

    /**
     * Sets the value of the fadvisingcontacttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFADVISINGCONTACTTYPE(String value) {
        this.fadvisingcontacttype = value;
    }

    /**
     * Gets the value of the fadvisingcontactname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFADVISINGCONTACTNAME() {
        return fadvisingcontactname;
    }

    /**
     * Sets the value of the fadvisingcontactname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFADVISINGCONTACTNAME(String value) {
        this.fadvisingcontactname = value;
    }

    /**
     * Gets the value of the fadvisingminamt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFADVISINGMINAMT() {
        return fadvisingminamt;
    }

    /**
     * Sets the value of the fadvisingminamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFADVISINGMINAMT(BigDecimal value) {
        this.fadvisingminamt = value;
    }

    /**
     * Gets the value of the fadvisingadvicesubtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFADVISINGADVICESUBTYPE() {
        return fadvisingadvicesubtype;
    }

    /**
     * Sets the value of the fadvisingadvicesubtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFADVISINGADVICESUBTYPE(String value) {
        this.fadvisingadvicesubtype = value;
    }

    /**
     * Gets the value of the fadvisingadvicetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFADVISINGADVICETYPE() {
        return fadvisingadvicetype;
    }

    /**
     * Sets the value of the fadvisingadvicetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFADVISINGADVICETYPE(String value) {
        this.fadvisingadvicetype = value;
    }

    /**
     * Gets the value of the fadvisingfeeadviceind property.
     * 
     */
    public boolean isFADVISINGFEEADVICEIND() {
        return fadvisingfeeadviceind;
    }

    /**
     * Sets the value of the fadvisingfeeadviceind property.
     * 
     */
    public void setFADVISINGFEEADVICEIND(boolean value) {
        this.fadvisingfeeadviceind = value;
    }

    /**
     * Gets the value of the fadvisingcradviceind property.
     * 
     */
    public boolean isFADVISINGCRADVICEIND() {
        return fadvisingcradviceind;
    }

    /**
     * Sets the value of the fadvisingcradviceind property.
     * 
     */
    public void setFADVISINGCRADVICEIND(boolean value) {
        this.fadvisingcradviceind = value;
    }

    /**
     * Gets the value of the fadvisingdradviceind property.
     * 
     */
    public boolean isFADVISINGDRADVICEIND() {
        return fadvisingdradviceind;
    }

    /**
     * Sets the value of the fadvisingdradviceind property.
     * 
     */
    public void setFADVISINGDRADVICEIND(boolean value) {
        this.fadvisingdradviceind = value;
    }

    /**
     * Gets the value of the fadvisingadvicetoparty property.
     * 
     * @return
     *     possible object is
     *     {@link AdviceToPartyType }
     *     
     */
    public AdviceToPartyType getFADVISINGADVICETOPARTY() {
        return fadvisingadvicetoparty;
    }

    /**
     * Sets the value of the fadvisingadvicetoparty property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdviceToPartyType }
     *     
     */
    public void setFADVISINGADVICETOPARTY(AdviceToPartyType value) {
        this.fadvisingadvicetoparty = value;
    }

    /**
     * Gets the value of the fadvisingadvcvehicle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFADVISINGADVCVEHICLE() {
        return fadvisingadvcvehicle;
    }

    /**
     * Sets the value of the fadvisingadvcvehicle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFADVISINGADVCVEHICLE(String value) {
        this.fadvisingadvcvehicle = value;
    }

    /**
     * Gets the value of the fadvisingtempid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFADVISINGTEMPID() {
        return fadvisingtempid;
    }

    /**
     * Sets the value of the fadvisingtempid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFADVISINGTEMPID(String value) {
        this.fadvisingtempid = value;
    }

    /**
     * Gets the value of the fadvisingacctype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFADVISINGACCTYPE() {
        return fadvisingacctype;
    }

    /**
     * Sets the value of the fadvisingacctype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFADVISINGACCTYPE(String value) {
        this.fadvisingacctype = value;
    }

}
