//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.28 at 09:00:52 PM CEST 
//


package org.example.model.com.fundtech.scl.commontypes;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AliasDetails12 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AliasDetails12"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="identifier" type="{http://fundtech.com/SCL/CommonTypes}IdentifierDetails1"/&gt;
 *         &lt;element name="servicer" type="{http://fundtech.com/SCL/CommonTypes}BICIdentifier"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AliasDetails12", propOrder = {
    "identifier",
    "servicer"
})
public class AliasDetails12 {

    @XmlElement(required = true)
    protected IdentifierDetails1 identifier;
    @XmlElement(required = true)
    protected String servicer;

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierDetails1 }
     *     
     */
    public IdentifierDetails1 getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierDetails1 }
     *     
     */
    public void setIdentifier(IdentifierDetails1 value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the servicer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServicer() {
        return servicer;
    }

    /**
     * Sets the value of the servicer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServicer(String value) {
        this.servicer = value;
    }

}
