//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.28 at 03:48:14 PM CEST 
//


package org.example.model.com.fundtech.scl.commontypes;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BulkReqInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BulkReqInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BulkInterfaceReqFileId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="OrigBulkInterfaceReqFileId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NbOfResponses" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BulkReqInfoType", propOrder = {
    "bulkInterfaceReqFileId",
    "origBulkInterfaceReqFileId",
    "nbOfResponses"
})
public class BulkReqInfoType {

    @XmlElement(name = "BulkInterfaceReqFileId", required = true)
    protected String bulkInterfaceReqFileId;
    @XmlElement(name = "OrigBulkInterfaceReqFileId")
    protected String origBulkInterfaceReqFileId;
    @XmlElement(name = "NbOfResponses")
    protected Integer nbOfResponses;

    /**
     * Gets the value of the bulkInterfaceReqFileId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBulkInterfaceReqFileId() {
        return bulkInterfaceReqFileId;
    }

    /**
     * Sets the value of the bulkInterfaceReqFileId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBulkInterfaceReqFileId(String value) {
        this.bulkInterfaceReqFileId = value;
    }

    /**
     * Gets the value of the origBulkInterfaceReqFileId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigBulkInterfaceReqFileId() {
        return origBulkInterfaceReqFileId;
    }

    /**
     * Sets the value of the origBulkInterfaceReqFileId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigBulkInterfaceReqFileId(String value) {
        this.origBulkInterfaceReqFileId = value;
    }

    /**
     * Gets the value of the nbOfResponses property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNbOfResponses() {
        return nbOfResponses;
    }

    /**
     * Sets the value of the nbOfResponses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNbOfResponses(Integer value) {
        this.nbOfResponses = value;
    }

}
