//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.28 at 09:00:52 PM CEST 
//


package org.example.model.com.fundtech.scl.commontypes;

import java.math.BigDecimal;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DebitSideType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DebitSideType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="P_DBT_MOP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="P_DBT_AMT" type="{http://fundtech.com/SCL/CommonTypes}AmountType" minOccurs="0"/&gt;
 *         &lt;element name="P_DBT_ACCT_NB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="P_DBT_FEE_ACCT_NB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="P_DBT_CROSS_CONV" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="P_DBT_CUST_CD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="P_DBT_FEE_ACCT_OFFICE" type="{http://fundtech.com/SCL/CommonTypes}OfficeType" minOccurs="0"/&gt;
 *         &lt;element name="P_DBT_FEE_PMT_CCY" type="{http://fundtech.com/SCL/CommonTypes}CurrencyType" minOccurs="0"/&gt;
 *         &lt;element name="P_DBT_FEE_POSTING_STS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="P_DBT_MID_RATE" type="{http://fundtech.com/SCL/CommonTypes}BaseOneRate" minOccurs="0"/&gt;
 *         &lt;element name="P_DBT_RATE" type="{http://fundtech.com/SCL/CommonTypes}BaseOneRate" minOccurs="0"/&gt;
 *         &lt;element name="P_DBT_COST_RATE" type="{http://fundtech.com/SCL/CommonTypes}BaseOneRate" minOccurs="0"/&gt;
 *         &lt;element name="P_DBT_RATE_USAGE_NM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="P_DBT_SPREAD" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="P_DBT_TX_CD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="P_DBT_AMT_STEP1" type="{http://fundtech.com/SCL/CommonTypes}AmountType" minOccurs="0"/&gt;
 *         &lt;element name="P_DBT_FEE_ACCT_CCY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="P_DBT_RATE_STEP1" type="{http://fundtech.com/SCL/CommonTypes}BaseOneRate" minOccurs="0"/&gt;
 *         &lt;element name="P_DBT_ACCT_CCY" type="{http://fundtech.com/SCL/CommonTypes}CurrencyType" minOccurs="0"/&gt;
 *         &lt;element name="P_DBT_RATE_STEP2" type="{http://fundtech.com/SCL/CommonTypes}BaseOneRate" minOccurs="0"/&gt;
 *         &lt;element name="P_DBT_ACCT_OFFICE" type="{http://fundtech.com/SCL/CommonTypes}OfficeType" minOccurs="0"/&gt;
 *         &lt;element name="P_DBT_TRIANGULATION_CCY" type="{http://fundtech.com/SCL/CommonTypes}CurrencyType" minOccurs="0"/&gt;
 *         &lt;element name="P_DBT_VD" type="{http://fundtech.com/SCL/CommonTypes}ISODate" minOccurs="0"/&gt;
 *         &lt;element name="P_DBT_APPLY_FEE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="P_DBT_BILL_IND" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="P_FOLLOWUP" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DebitSideType", propOrder = {

})
public class DebitSideType {

    @XmlElement(name = "P_DBT_MOP")
    protected String pdbtmop;
    @XmlElement(name = "P_DBT_AMT")
    protected BigDecimal pdbtamt;
    @XmlElement(name = "P_DBT_ACCT_NB")
    protected String pdbtacctnb;
    @XmlElement(name = "P_DBT_FEE_ACCT_NB")
    protected String pdbtfeeacctnb;
    @XmlElement(name = "P_DBT_CROSS_CONV", defaultValue = "0")
    protected Integer pdbtcrossconv;
    @XmlElement(name = "P_DBT_CUST_CD")
    protected String pdbtcustcd;
    @XmlElement(name = "P_DBT_FEE_ACCT_OFFICE")
    protected String pdbtfeeacctoffice;
    @XmlElement(name = "P_DBT_FEE_PMT_CCY")
    protected String pdbtfeepmtccy;
    @XmlElement(name = "P_DBT_FEE_POSTING_STS")
    protected String pdbtfeepostingsts;
    @XmlElement(name = "P_DBT_MID_RATE")
    protected BigDecimal pdbtmidrate;
    @XmlElement(name = "P_DBT_RATE")
    protected BigDecimal pdbtrate;
    @XmlElement(name = "P_DBT_COST_RATE")
    protected BigDecimal pdbtcostrate;
    @XmlElement(name = "P_DBT_RATE_USAGE_NM")
    protected String pdbtrateusagenm;
    @XmlElement(name = "P_DBT_SPREAD")
    protected BigDecimal pdbtspread;
    @XmlElement(name = "P_DBT_TX_CD")
    protected String pdbttxcd;
    @XmlElement(name = "P_DBT_AMT_STEP1")
    protected BigDecimal pdbtamtstep1;
    @XmlElement(name = "P_DBT_FEE_ACCT_CCY")
    protected String pdbtfeeacctccy;
    @XmlElement(name = "P_DBT_RATE_STEP1")
    protected BigDecimal pdbtratestep1;
    @XmlElement(name = "P_DBT_ACCT_CCY")
    protected String pdbtacctccy;
    @XmlElement(name = "P_DBT_RATE_STEP2")
    protected BigDecimal pdbtratestep2;
    @XmlElement(name = "P_DBT_ACCT_OFFICE")
    protected String pdbtacctoffice;
    @XmlElement(name = "P_DBT_TRIANGULATION_CCY")
    protected String pdbttriangulationccy;
    @XmlElement(name = "P_DBT_VD")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar pdbtvd;
    @XmlElement(name = "P_DBT_APPLY_FEE")
    protected String pdbtapplyfee;
    @XmlElement(name = "P_DBT_BILL_IND")
    protected Boolean pdbtbillind;
    @XmlElement(name = "P_FOLLOWUP")
    protected Boolean pfollowup;

    /**
     * Gets the value of the pdbtmop property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPDBTMOP() {
        return pdbtmop;
    }

    /**
     * Sets the value of the pdbtmop property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPDBTMOP(String value) {
        this.pdbtmop = value;
    }

    /**
     * Gets the value of the pdbtamt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPDBTAMT() {
        return pdbtamt;
    }

    /**
     * Sets the value of the pdbtamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPDBTAMT(BigDecimal value) {
        this.pdbtamt = value;
    }

    /**
     * Gets the value of the pdbtacctnb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPDBTACCTNB() {
        return pdbtacctnb;
    }

    /**
     * Sets the value of the pdbtacctnb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPDBTACCTNB(String value) {
        this.pdbtacctnb = value;
    }

    /**
     * Gets the value of the pdbtfeeacctnb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPDBTFEEACCTNB() {
        return pdbtfeeacctnb;
    }

    /**
     * Sets the value of the pdbtfeeacctnb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPDBTFEEACCTNB(String value) {
        this.pdbtfeeacctnb = value;
    }

    /**
     * Gets the value of the pdbtcrossconv property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPDBTCROSSCONV() {
        return pdbtcrossconv;
    }

    /**
     * Sets the value of the pdbtcrossconv property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPDBTCROSSCONV(Integer value) {
        this.pdbtcrossconv = value;
    }

    /**
     * Gets the value of the pdbtcustcd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPDBTCUSTCD() {
        return pdbtcustcd;
    }

    /**
     * Sets the value of the pdbtcustcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPDBTCUSTCD(String value) {
        this.pdbtcustcd = value;
    }

    /**
     * Gets the value of the pdbtfeeacctoffice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPDBTFEEACCTOFFICE() {
        return pdbtfeeacctoffice;
    }

    /**
     * Sets the value of the pdbtfeeacctoffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPDBTFEEACCTOFFICE(String value) {
        this.pdbtfeeacctoffice = value;
    }

    /**
     * Gets the value of the pdbtfeepmtccy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPDBTFEEPMTCCY() {
        return pdbtfeepmtccy;
    }

    /**
     * Sets the value of the pdbtfeepmtccy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPDBTFEEPMTCCY(String value) {
        this.pdbtfeepmtccy = value;
    }

    /**
     * Gets the value of the pdbtfeepostingsts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPDBTFEEPOSTINGSTS() {
        return pdbtfeepostingsts;
    }

    /**
     * Sets the value of the pdbtfeepostingsts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPDBTFEEPOSTINGSTS(String value) {
        this.pdbtfeepostingsts = value;
    }

    /**
     * Gets the value of the pdbtmidrate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPDBTMIDRATE() {
        return pdbtmidrate;
    }

    /**
     * Sets the value of the pdbtmidrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPDBTMIDRATE(BigDecimal value) {
        this.pdbtmidrate = value;
    }

    /**
     * Gets the value of the pdbtrate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPDBTRATE() {
        return pdbtrate;
    }

    /**
     * Sets the value of the pdbtrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPDBTRATE(BigDecimal value) {
        this.pdbtrate = value;
    }

    /**
     * Gets the value of the pdbtcostrate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPDBTCOSTRATE() {
        return pdbtcostrate;
    }

    /**
     * Sets the value of the pdbtcostrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPDBTCOSTRATE(BigDecimal value) {
        this.pdbtcostrate = value;
    }

    /**
     * Gets the value of the pdbtrateusagenm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPDBTRATEUSAGENM() {
        return pdbtrateusagenm;
    }

    /**
     * Sets the value of the pdbtrateusagenm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPDBTRATEUSAGENM(String value) {
        this.pdbtrateusagenm = value;
    }

    /**
     * Gets the value of the pdbtspread property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPDBTSPREAD() {
        return pdbtspread;
    }

    /**
     * Sets the value of the pdbtspread property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPDBTSPREAD(BigDecimal value) {
        this.pdbtspread = value;
    }

    /**
     * Gets the value of the pdbttxcd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPDBTTXCD() {
        return pdbttxcd;
    }

    /**
     * Sets the value of the pdbttxcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPDBTTXCD(String value) {
        this.pdbttxcd = value;
    }

    /**
     * Gets the value of the pdbtamtstep1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPDBTAMTSTEP1() {
        return pdbtamtstep1;
    }

    /**
     * Sets the value of the pdbtamtstep1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPDBTAMTSTEP1(BigDecimal value) {
        this.pdbtamtstep1 = value;
    }

    /**
     * Gets the value of the pdbtfeeacctccy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPDBTFEEACCTCCY() {
        return pdbtfeeacctccy;
    }

    /**
     * Sets the value of the pdbtfeeacctccy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPDBTFEEACCTCCY(String value) {
        this.pdbtfeeacctccy = value;
    }

    /**
     * Gets the value of the pdbtratestep1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPDBTRATESTEP1() {
        return pdbtratestep1;
    }

    /**
     * Sets the value of the pdbtratestep1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPDBTRATESTEP1(BigDecimal value) {
        this.pdbtratestep1 = value;
    }

    /**
     * Gets the value of the pdbtacctccy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPDBTACCTCCY() {
        return pdbtacctccy;
    }

    /**
     * Sets the value of the pdbtacctccy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPDBTACCTCCY(String value) {
        this.pdbtacctccy = value;
    }

    /**
     * Gets the value of the pdbtratestep2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPDBTRATESTEP2() {
        return pdbtratestep2;
    }

    /**
     * Sets the value of the pdbtratestep2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPDBTRATESTEP2(BigDecimal value) {
        this.pdbtratestep2 = value;
    }

    /**
     * Gets the value of the pdbtacctoffice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPDBTACCTOFFICE() {
        return pdbtacctoffice;
    }

    /**
     * Sets the value of the pdbtacctoffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPDBTACCTOFFICE(String value) {
        this.pdbtacctoffice = value;
    }

    /**
     * Gets the value of the pdbttriangulationccy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPDBTTRIANGULATIONCCY() {
        return pdbttriangulationccy;
    }

    /**
     * Sets the value of the pdbttriangulationccy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPDBTTRIANGULATIONCCY(String value) {
        this.pdbttriangulationccy = value;
    }

    /**
     * Gets the value of the pdbtvd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPDBTVD() {
        return pdbtvd;
    }

    /**
     * Sets the value of the pdbtvd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPDBTVD(XMLGregorianCalendar value) {
        this.pdbtvd = value;
    }

    /**
     * Gets the value of the pdbtapplyfee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPDBTAPPLYFEE() {
        return pdbtapplyfee;
    }

    /**
     * Sets the value of the pdbtapplyfee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPDBTAPPLYFEE(String value) {
        this.pdbtapplyfee = value;
    }

    /**
     * Gets the value of the pdbtbillind property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPDBTBILLIND() {
        return pdbtbillind;
    }

    /**
     * Sets the value of the pdbtbillind property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPDBTBILLIND(Boolean value) {
        this.pdbtbillind = value;
    }

    /**
     * Gets the value of the pfollowup property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPFOLLOWUP() {
        return pfollowup;
    }

    /**
     * Sets the value of the pfollowup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPFOLLOWUP(Boolean value) {
        this.pfollowup = value;
    }

}
