//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.28 at 03:48:14 PM CEST 
//


package org.example.model.com.fundtech.scl.commontypes;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DOUBLE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DOUBLE"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://fundtech.com/SCL/CommonTypes}MsgTableEntryBaseType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OLD_VALUE" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="NEW_VALUE" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DOUBLE", propOrder = {
    "oldvalue",
    "newvalue"
})
public class DOUBLE
    extends MsgTableEntryBaseType
{

    @XmlElement(name = "OLD_VALUE")
    protected Double oldvalue;
    @XmlElement(name = "NEW_VALUE")
    protected Double newvalue;
    @XmlAttribute(name = "value")
    protected Double value;

    /**
     * Gets the value of the oldvalue property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getOLDVALUE() {
        return oldvalue;
    }

    /**
     * Sets the value of the oldvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setOLDVALUE(Double value) {
        this.oldvalue = value;
    }

    /**
     * Gets the value of the newvalue property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getNEWVALUE() {
        return newvalue;
    }

    /**
     * Sets the value of the newvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setNEWVALUE(Double value) {
        this.newvalue = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setValue(Double value) {
        this.value = value;
    }

}
