//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.28 at 09:00:52 PM CEST 
//


package org.example.model.com.fundtech.scl.commontypes;

import java.math.BigDecimal;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ForwardContractLineType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ForwardContractLineType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="F_FC_CONTRACT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_FC_AMOUNT" type="{http://fundtech.com/SCL/CommonTypes}AmountType" minOccurs="0"/&gt;
 *         &lt;element name="F_FC_RATE" type="{http://fundtech.com/SCL/CommonTypes}BaseOneRate" minOccurs="0"/&gt;
 *         &lt;element name="F_FC_CURRENCY1" type="{http://fundtech.com/SCL/CommonTypes}CurrencyType"/&gt;
 *         &lt;element name="F_FC_CURRENCY2" type="{http://fundtech.com/SCL/CommonTypes}CurrencyType"/&gt;
 *         &lt;element name="F_FC_SPREAD" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="F_FC_SPREAD_UNITS" type="{http://fundtech.com/SCL/CommonTypes}SpreadUnitsType" minOccurs="0"/&gt;
 *         &lt;element name="F_FC_MID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_FC_CONVERSION_TYPE" type="{http://fundtech.com/SCL/CommonTypes}FCConversionType" minOccurs="0"/&gt;
 *         &lt;element name="F_FC_FORWARD_CONTRACT" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="F_FC_CUSTOMER_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_FC_MANUAL_SPREAD" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="F_FC_AMOUNT_TO" type="{http://fundtech.com/SCL/CommonTypes}AmountType" minOccurs="0"/&gt;
 *         &lt;element name="F_FC_TARGET_RATE" type="{http://fundtech.com/SCL/CommonTypes}BaseOneRate" minOccurs="0"/&gt;
 *         &lt;element name="F_FC_LATEST_DATE" type="{http://fundtech.com/SCL/CommonTypes}ISODate" minOccurs="0"/&gt;
 *         &lt;element name="F_FC_COST_RATE" type="{http://fundtech.com/SCL/CommonTypes}BaseOneRate" minOccurs="0"/&gt;
 *         &lt;element name="F_FC_RATE_DIRECTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ForwardContractLineType", propOrder = {
    "ffccontract",
    "ffcamount",
    "ffcrate",
    "ffccurrency1",
    "ffccurrency2",
    "ffcspread",
    "ffcspreadunits",
    "ffcmid",
    "ffcconversiontype",
    "ffcforwardcontract",
    "ffccustomerid",
    "ffcmanualspread",
    "ffcamountto",
    "ffctargetrate",
    "ffclatestdate",
    "ffccostrate",
    "ffcratedirection"
})
public class ForwardContractLineType {

    @XmlElement(name = "F_FC_CONTRACT")
    protected String ffccontract;
    @XmlElement(name = "F_FC_AMOUNT")
    protected BigDecimal ffcamount;
    @XmlElement(name = "F_FC_RATE")
    protected BigDecimal ffcrate;
    @XmlElement(name = "F_FC_CURRENCY1", required = true)
    protected String ffccurrency1;
    @XmlElement(name = "F_FC_CURRENCY2", required = true)
    protected String ffccurrency2;
    @XmlElement(name = "F_FC_SPREAD")
    protected BigDecimal ffcspread;
    @XmlElement(name = "F_FC_SPREAD_UNITS")
    @XmlSchemaType(name = "string")
    protected SpreadUnitsType ffcspreadunits;
    @XmlElement(name = "F_FC_MID")
    protected String ffcmid;
    @XmlElement(name = "F_FC_CONVERSION_TYPE")
    @XmlSchemaType(name = "string")
    protected FCConversionType ffcconversiontype;
    @XmlElement(name = "F_FC_FORWARD_CONTRACT")
    protected Long ffcforwardcontract;
    @XmlElement(name = "F_FC_CUSTOMER_ID")
    protected String ffccustomerid;
    @XmlElement(name = "F_FC_MANUAL_SPREAD")
    protected BigDecimal ffcmanualspread;
    @XmlElement(name = "F_FC_AMOUNT_TO")
    protected BigDecimal ffcamountto;
    @XmlElement(name = "F_FC_TARGET_RATE")
    protected BigDecimal ffctargetrate;
    @XmlElement(name = "F_FC_LATEST_DATE")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar ffclatestdate;
    @XmlElement(name = "F_FC_COST_RATE")
    protected BigDecimal ffccostrate;
    @XmlElement(name = "F_FC_RATE_DIRECTION")
    protected String ffcratedirection;

    /**
     * Gets the value of the ffccontract property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFFCCONTRACT() {
        return ffccontract;
    }

    /**
     * Sets the value of the ffccontract property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFFCCONTRACT(String value) {
        this.ffccontract = value;
    }

    /**
     * Gets the value of the ffcamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFFCAMOUNT() {
        return ffcamount;
    }

    /**
     * Sets the value of the ffcamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFFCAMOUNT(BigDecimal value) {
        this.ffcamount = value;
    }

    /**
     * Gets the value of the ffcrate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFFCRATE() {
        return ffcrate;
    }

    /**
     * Sets the value of the ffcrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFFCRATE(BigDecimal value) {
        this.ffcrate = value;
    }

    /**
     * Gets the value of the ffccurrency1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFFCCURRENCY1() {
        return ffccurrency1;
    }

    /**
     * Sets the value of the ffccurrency1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFFCCURRENCY1(String value) {
        this.ffccurrency1 = value;
    }

    /**
     * Gets the value of the ffccurrency2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFFCCURRENCY2() {
        return ffccurrency2;
    }

    /**
     * Sets the value of the ffccurrency2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFFCCURRENCY2(String value) {
        this.ffccurrency2 = value;
    }

    /**
     * Gets the value of the ffcspread property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFFCSPREAD() {
        return ffcspread;
    }

    /**
     * Sets the value of the ffcspread property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFFCSPREAD(BigDecimal value) {
        this.ffcspread = value;
    }

    /**
     * Gets the value of the ffcspreadunits property.
     * 
     * @return
     *     possible object is
     *     {@link SpreadUnitsType }
     *     
     */
    public SpreadUnitsType getFFCSPREADUNITS() {
        return ffcspreadunits;
    }

    /**
     * Sets the value of the ffcspreadunits property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpreadUnitsType }
     *     
     */
    public void setFFCSPREADUNITS(SpreadUnitsType value) {
        this.ffcspreadunits = value;
    }

    /**
     * Gets the value of the ffcmid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFFCMID() {
        return ffcmid;
    }

    /**
     * Sets the value of the ffcmid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFFCMID(String value) {
        this.ffcmid = value;
    }

    /**
     * Gets the value of the ffcconversiontype property.
     * 
     * @return
     *     possible object is
     *     {@link FCConversionType }
     *     
     */
    public FCConversionType getFFCCONVERSIONTYPE() {
        return ffcconversiontype;
    }

    /**
     * Sets the value of the ffcconversiontype property.
     * 
     * @param value
     *     allowed object is
     *     {@link FCConversionType }
     *     
     */
    public void setFFCCONVERSIONTYPE(FCConversionType value) {
        this.ffcconversiontype = value;
    }

    /**
     * Gets the value of the ffcforwardcontract property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getFFCFORWARDCONTRACT() {
        return ffcforwardcontract;
    }

    /**
     * Sets the value of the ffcforwardcontract property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setFFCFORWARDCONTRACT(Long value) {
        this.ffcforwardcontract = value;
    }

    /**
     * Gets the value of the ffccustomerid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFFCCUSTOMERID() {
        return ffccustomerid;
    }

    /**
     * Sets the value of the ffccustomerid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFFCCUSTOMERID(String value) {
        this.ffccustomerid = value;
    }

    /**
     * Gets the value of the ffcmanualspread property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFFCMANUALSPREAD() {
        return ffcmanualspread;
    }

    /**
     * Sets the value of the ffcmanualspread property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFFCMANUALSPREAD(BigDecimal value) {
        this.ffcmanualspread = value;
    }

    /**
     * Gets the value of the ffcamountto property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFFCAMOUNTTO() {
        return ffcamountto;
    }

    /**
     * Sets the value of the ffcamountto property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFFCAMOUNTTO(BigDecimal value) {
        this.ffcamountto = value;
    }

    /**
     * Gets the value of the ffctargetrate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFFCTARGETRATE() {
        return ffctargetrate;
    }

    /**
     * Sets the value of the ffctargetrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFFCTARGETRATE(BigDecimal value) {
        this.ffctargetrate = value;
    }

    /**
     * Gets the value of the ffclatestdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFFCLATESTDATE() {
        return ffclatestdate;
    }

    /**
     * Sets the value of the ffclatestdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFFCLATESTDATE(XMLGregorianCalendar value) {
        this.ffclatestdate = value;
    }

    /**
     * Gets the value of the ffccostrate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFFCCOSTRATE() {
        return ffccostrate;
    }

    /**
     * Sets the value of the ffccostrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFFCCOSTRATE(BigDecimal value) {
        this.ffccostrate = value;
    }

    /**
     * Gets the value of the ffcratedirection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFFCRATEDIRECTION() {
        return ffcratedirection;
    }

    /**
     * Sets the value of the ffcratedirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFFCRATEDIRECTION(String value) {
        this.ffcratedirection = value;
    }

}
