//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.28 at 03:48:14 PM CEST 
//


package org.example.model.com.fundtech.scl.commontypes;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LiquidityCheckInfRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LiquidityCheckInfRecord"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="F_LIQ_INFO_ACCNO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_LIQ_INFO_ACC_CURRENCY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_LIQ_INFO_AMOUNT" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="F_LIQ_INFO_VALUE_DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_LIQ_INFO_EARMARK_REF" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LiquidityCheckInfRecord", propOrder = {
    "fliqinfoaccno",
    "fliqinfoacccurrency",
    "fliqinfoamount",
    "fliqinfovaluedate",
    "fliqinfoearmarkref"
})
public class LiquidityCheckInfRecord {

    @XmlElement(name = "F_LIQ_INFO_ACCNO")
    protected String fliqinfoaccno;
    @XmlElement(name = "F_LIQ_INFO_ACC_CURRENCY")
    protected String fliqinfoacccurrency;
    @XmlElement(name = "F_LIQ_INFO_AMOUNT")
    protected BigDecimal fliqinfoamount;
    @XmlElement(name = "F_LIQ_INFO_VALUE_DATE")
    protected String fliqinfovaluedate;
    @XmlElement(name = "F_LIQ_INFO_EARMARK_REF")
    protected String fliqinfoearmarkref;

    /**
     * Gets the value of the fliqinfoaccno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFLIQINFOACCNO() {
        return fliqinfoaccno;
    }

    /**
     * Sets the value of the fliqinfoaccno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFLIQINFOACCNO(String value) {
        this.fliqinfoaccno = value;
    }

    /**
     * Gets the value of the fliqinfoacccurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFLIQINFOACCCURRENCY() {
        return fliqinfoacccurrency;
    }

    /**
     * Sets the value of the fliqinfoacccurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFLIQINFOACCCURRENCY(String value) {
        this.fliqinfoacccurrency = value;
    }

    /**
     * Gets the value of the fliqinfoamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFLIQINFOAMOUNT() {
        return fliqinfoamount;
    }

    /**
     * Sets the value of the fliqinfoamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFLIQINFOAMOUNT(BigDecimal value) {
        this.fliqinfoamount = value;
    }

    /**
     * Gets the value of the fliqinfovaluedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFLIQINFOVALUEDATE() {
        return fliqinfovaluedate;
    }

    /**
     * Sets the value of the fliqinfovaluedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFLIQINFOVALUEDATE(String value) {
        this.fliqinfovaluedate = value;
    }

    /**
     * Gets the value of the fliqinfoearmarkref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFLIQINFOEARMARKREF() {
        return fliqinfoearmarkref;
    }

    /**
     * Sets the value of the fliqinfoearmarkref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFLIQINFOEARMARKREF(String value) {
        this.fliqinfoearmarkref = value;
    }

}
