//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.28 at 03:48:14 PM CEST 
//


package org.example.model.com.fundtech.scl.commontypes;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for M_INSTG_AGT_PROFILEType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="M_INSTG_AGT_PROFILEType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="F_INSTG_CUST_ABA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_INSTG_CUST_SWIFT_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_INSTG_CUST_ALIAS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "M_INSTG_AGT_PROFILEType", propOrder = {

})
public class MINSTGAGTPROFILEType {

    @XmlElement(name = "F_INSTG_CUST_ABA")
    protected String finstgcustaba;
    @XmlElement(name = "F_INSTG_CUST_SWIFT_ID")
    protected String finstgcustswiftid;
    @XmlElement(name = "F_INSTG_CUST_ALIAS")
    protected String finstgcustalias;

    /**
     * Gets the value of the finstgcustaba property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFINSTGCUSTABA() {
        return finstgcustaba;
    }

    /**
     * Sets the value of the finstgcustaba property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFINSTGCUSTABA(String value) {
        this.finstgcustaba = value;
    }

    /**
     * Gets the value of the finstgcustswiftid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFINSTGCUSTSWIFTID() {
        return finstgcustswiftid;
    }

    /**
     * Sets the value of the finstgcustswiftid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFINSTGCUSTSWIFTID(String value) {
        this.finstgcustswiftid = value;
    }

    /**
     * Gets the value of the finstgcustalias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFINSTGCUSTALIAS() {
        return finstgcustalias;
    }

    /**
     * Sets the value of the finstgcustalias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFINSTGCUSTALIAS(String value) {
        this.finstgcustalias = value;
    }

}
