//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.28 at 03:48:14 PM CEST 
//


package org.example.model.com.fundtech.scl.commontypes;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 *         map("MANUAL_FEE", "F_MSG_FEES_MANUAL_FEE");
 *         map("DEDUCT_FROM", "F_MSG_FEES_DEDUCT_FROM");
 *         map("FEE_ACC_AMOUNT", "F_MSG_FEES_FEE_ACC_AMOUNT");
 *         map("FEE_AMOUNT", "F_MSG_FEES_FEE_AMOUNT");
 *         map("FEE_AMOUNT_IN_PMT_CCY", "F_MSG_FEES_FEE_AMT_IN_PMT_CCY");
 *         map("APPLY", "F_MSG_FEES_FEE_APPLY");
 *         map("FEE_BASE_AMOUNT", "F_MSG_FEES_FEE_BASE_AMOUNT");
 *         map("FEE_CURRENCY", "F_MSG_FEES_FEE_CURRENCY");
 *         map("FEE_FORMULA_UID", "F_MSG_FEES_FEE_FORMULA_UID");
 *         map("FEE_MONITOR", "F_MSG_FEES_FEE_MONITOR");
 *         map("FEE_PNL_ACCOUNT_CURRENCY", "F_MSG_FEES_FEE_PNL_ACC_CUR");
 *         map("FEE_PNL_ACC_NO", "F_MSG_FEES_FEE_PNL_ACC_NO ");
 *         map("FEE_PNL_AMOUNT", "F_MSG_FEES_FEE_PNL_AMOUNT");
 *         map("FEE_TYPE_UID", "F_MSG_FEES_FEE_TYPE_UID");
 *         map("ORIG_FEE_AMOUNT", "F_MSG_FEES_ORIG_FEE_AMOUNT");
 *         map("PAYING_PARTY", "F_MSG_FEES_PAYING_PARTY");
 *         map("FEE_PNL_ACC_OFFICE", "F_MSG_FEES_PNL_ACC_OFFICE");
 *         map("PNL_POSTING_STS", "F_MSG_FEES_PNL_POSTING_STS");
 *         map("UNWIND_FEE", "F_MSG_FEES_UNWIND_FEE") ;
 *         map("TAX_CODE", "F_MSG_FEES_FEE_TAX_CODE");
 *         map("TYPE_NAME", "F_MSG_FEES_FEE_TYPE_NAME");
 *         map("FORMULA_NAME", "F_MSG_FEES_FEE_FORMULA_NAME");
 *         map("FEE_TYPE_DESCRIPTION", "F_MSG_FEES_FEE_TYPE_DESCRIPTION");
 * 
 * 
 * 
 * 
 *       
 * 
 * <p>Java class for MsgFeesLineType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MsgFeesLineType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="F_MSG_FEES_FEE_ACC_UID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_MANUAL_FEE" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_FEE_FORMULA_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_FEE_TYPE_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_DEDUCT_FROM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_FEE_ACC_AMOUNT" type="{http://fundtech.com/SCL/CommonTypes}AmountType" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_FEE_ACC_AMT_RATE" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_FEE_AMOUNT" type="{http://fundtech.com/SCL/CommonTypes}AmountType" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_FEE_AMT_IN_PMT_CCY" type="{http://fundtech.com/SCL/CommonTypes}AmountType" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_FEE_APPLY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_FEE_BASE_AMOUNT" type="{http://fundtech.com/SCL/CommonTypes}AmountType" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_FEE_CURRENCY" type="{http://fundtech.com/SCL/CommonTypes}CurrencyType" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_FEE_FORMULA_UID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_FEE_MONITOR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_FEE_PNL_ACC_CUR" type="{http://fundtech.com/SCL/CommonTypes}CurrencyType" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_FEE_PNL_ACC_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_FEE_PNL_AMOUNT" type="{http://fundtech.com/SCL/CommonTypes}AmountType" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_FEE_TYPE_UID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_ORIG_FEE_AMOUNT" type="{http://fundtech.com/SCL/CommonTypes}AmountType" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_PAYING_PARTY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_PNL_ACC_OFFICE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_PNL_POSTING_STS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_UNWIND_FEE" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_TAX_AMOUNT" type="{http://fundtech.com/SCL/CommonTypes}AmountType" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_TAX_BASE_AMOUNT" type="{http://fundtech.com/SCL/CommonTypes}AmountType" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_REBATE" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_BASE_2_FEEACCT_RATE" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_BASE_2_FEEACCT_VER" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_BASE_AMT_RATE_VER" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_FEE_BASE_CUR_RATE" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_TAX_AMT_PNL_CCY" type="{http://fundtech.com/SCL/CommonTypes}AmountType" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_TAX_BASE_CUR_RATE" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_TAX_FROM_PAYMENT" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_TAX_ON_TAX_AMOUNT" type="{http://fundtech.com/SCL/CommonTypes}AmountType" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_TAX_PNL_ACCT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_TAX_PNL_ACCT_OFFICE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_TAX_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_TAX_PNL_ACCT_CCY" type="{http://fundtech.com/SCL/CommonTypes}CurrencyType" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_TAX_TO_PNL_AC_DT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_TAX_TO_PNL_CCY_RATE" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_TAX_TO_PNL_CCY_VER" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_PNL_ACC_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_MID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_FEE_POST_NTRY_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_PNL_POST_NTRY_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_TX_POST_NTRY_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_TX_PNL_POST_NTRY_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_TX_ON_TAX_NTRY_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_TXONTX_PNL_NTRY_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_TAX_PRSTG_RATE" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_FEE_TAX_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="F_MSG_FEES_FEE_TYPE_DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MsgFeesLineType", propOrder = {

})
public class MsgFeesLineType {

    @XmlElement(name = "F_MSG_FEES_FEE_ACC_UID")
    protected String fmsgfeesfeeaccuid;
    @XmlElement(name = "F_MSG_FEES_MANUAL_FEE")
    protected Integer fmsgfeesmanualfee;
    @XmlElement(name = "F_MSG_FEES_FEE_FORMULA_NAME")
    protected String fmsgfeesfeeformulaname;
    @XmlElement(name = "F_MSG_FEES_FEE_TYPE_NAME")
    protected String fmsgfeesfeetypename;
    @XmlElement(name = "F_MSG_FEES_DEDUCT_FROM")
    protected String fmsgfeesdeductfrom;
    @XmlElement(name = "F_MSG_FEES_FEE_ACC_AMOUNT")
    protected BigDecimal fmsgfeesfeeaccamount;
    @XmlElement(name = "F_MSG_FEES_FEE_ACC_AMT_RATE")
    protected BigDecimal fmsgfeesfeeaccamtrate;
    @XmlElement(name = "F_MSG_FEES_FEE_AMOUNT")
    protected BigDecimal fmsgfeesfeeamount;
    @XmlElement(name = "F_MSG_FEES_FEE_AMT_IN_PMT_CCY")
    protected BigDecimal fmsgfeesfeeamtinpmtccy;
    @XmlElement(name = "F_MSG_FEES_FEE_APPLY")
    protected String fmsgfeesfeeapply;
    @XmlElement(name = "F_MSG_FEES_FEE_BASE_AMOUNT")
    protected BigDecimal fmsgfeesfeebaseamount;
    @XmlElement(name = "F_MSG_FEES_FEE_CURRENCY")
    protected String fmsgfeesfeecurrency;
    @XmlElement(name = "F_MSG_FEES_FEE_FORMULA_UID")
    protected String fmsgfeesfeeformulauid;
    @XmlElement(name = "F_MSG_FEES_FEE_MONITOR")
    protected String fmsgfeesfeemonitor;
    @XmlElement(name = "F_MSG_FEES_FEE_PNL_ACC_CUR")
    protected String fmsgfeesfeepnlacccur;
    @XmlElement(name = "F_MSG_FEES_FEE_PNL_ACC_NO")
    protected String fmsgfeesfeepnlaccno;
    @XmlElement(name = "F_MSG_FEES_FEE_PNL_AMOUNT")
    protected BigDecimal fmsgfeesfeepnlamount;
    @XmlElement(name = "F_MSG_FEES_FEE_TYPE_UID")
    protected String fmsgfeesfeetypeuid;
    @XmlElement(name = "F_MSG_FEES_ORIG_FEE_AMOUNT")
    protected BigDecimal fmsgfeesorigfeeamount;
    @XmlElement(name = "F_MSG_FEES_PAYING_PARTY")
    protected String fmsgfeespayingparty;
    @XmlElement(name = "F_MSG_FEES_PNL_ACC_OFFICE")
    protected String fmsgfeespnlaccoffice;
    @XmlElement(name = "F_MSG_FEES_PNL_POSTING_STS")
    protected String fmsgfeespnlpostingsts;
    @XmlElement(name = "F_MSG_FEES_UNWIND_FEE")
    protected Boolean fmsgfeesunwindfee;
    @XmlElement(name = "F_MSG_FEES_TAX_AMOUNT")
    protected BigDecimal fmsgfeestaxamount;
    @XmlElement(name = "F_MSG_FEES_TAX_BASE_AMOUNT")
    protected BigDecimal fmsgfeestaxbaseamount;
    @XmlElement(name = "F_MSG_FEES_REBATE")
    protected BigDecimal fmsgfeesrebate;
    @XmlElement(name = "F_MSG_FEES_BASE_2_FEEACCT_RATE")
    protected BigDecimal fmsgfeesbase2FEEACCTRATE;
    @XmlElement(name = "F_MSG_FEES_BASE_2_FEEACCT_VER")
    protected BigDecimal fmsgfeesbase2FEEACCTVER;
    @XmlElement(name = "F_MSG_FEES_BASE_AMT_RATE_VER")
    protected BigDecimal fmsgfeesbaseamtratever;
    @XmlElement(name = "F_MSG_FEES_FEE_BASE_CUR_RATE")
    protected BigDecimal fmsgfeesfeebasecurrate;
    @XmlElement(name = "F_MSG_FEES_TAX_AMT_PNL_CCY")
    protected BigDecimal fmsgfeestaxamtpnlccy;
    @XmlElement(name = "F_MSG_FEES_TAX_BASE_CUR_RATE")
    protected BigDecimal fmsgfeestaxbasecurrate;
    @XmlElement(name = "F_MSG_FEES_TAX_FROM_PAYMENT")
    protected Integer fmsgfeestaxfrompayment;
    @XmlElement(name = "F_MSG_FEES_TAX_ON_TAX_AMOUNT")
    protected BigDecimal fmsgfeestaxontaxamount;
    @XmlElement(name = "F_MSG_FEES_TAX_PNL_ACCT")
    protected String fmsgfeestaxpnlacct;
    @XmlElement(name = "F_MSG_FEES_TAX_PNL_ACCT_OFFICE")
    protected String fmsgfeestaxpnlacctoffice;
    @XmlElement(name = "F_MSG_FEES_TAX_NAME")
    protected String fmsgfeestaxname;
    @XmlElement(name = "F_MSG_FEES_TAX_PNL_ACCT_CCY")
    protected String fmsgfeestaxpnlacctccy;
    @XmlElement(name = "F_MSG_FEES_TAX_TO_PNL_AC_DT")
    protected String fmsgfeestaxtopnlacdt;
    @XmlElement(name = "F_MSG_FEES_TAX_TO_PNL_CCY_RATE")
    protected BigDecimal fmsgfeestaxtopnlccyrate;
    @XmlElement(name = "F_MSG_FEES_TAX_TO_PNL_CCY_VER")
    protected BigDecimal fmsgfeestaxtopnlccyver;
    @XmlElement(name = "F_MSG_FEES_PNL_ACC_NO")
    protected String fmsgfeespnlaccno;
    @XmlElement(name = "F_MSG_FEES_MID")
    protected String fmsgfeesmid;
    @XmlElement(name = "F_MSG_FEES_FEE_POST_NTRY_ID")
    protected String fmsgfeesfeepostntryid;
    @XmlElement(name = "F_MSG_FEES_PNL_POST_NTRY_ID")
    protected String fmsgfeespnlpostntryid;
    @XmlElement(name = "F_MSG_FEES_TX_POST_NTRY_ID")
    protected String fmsgfeestxpostntryid;
    @XmlElement(name = "F_MSG_FEES_TX_PNL_POST_NTRY_ID")
    protected String fmsgfeestxpnlpostntryid;
    @XmlElement(name = "F_MSG_FEES_TX_ON_TAX_NTRY_ID")
    protected String fmsgfeestxontaxntryid;
    @XmlElement(name = "F_MSG_FEES_TXONTX_PNL_NTRY_ID")
    protected String fmsgfeestxontxpnlntryid;
    @XmlElement(name = "F_MSG_FEES_TAX_PRSTG_RATE")
    protected BigDecimal fmsgfeestaxprstgrate;
    @XmlElement(name = "F_MSG_FEES_FEE_TAX_CODE")
    protected String fmsgfeesfeetaxcode;
    @XmlElement(name = "F_MSG_FEES_FEE_TYPE_DESCRIPTION")
    protected String fmsgfeesfeetypedescription;

    /**
     * Gets the value of the fmsgfeesfeeaccuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESFEEACCUID() {
        return fmsgfeesfeeaccuid;
    }

    /**
     * Sets the value of the fmsgfeesfeeaccuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESFEEACCUID(String value) {
        this.fmsgfeesfeeaccuid = value;
    }

    /**
     * Gets the value of the fmsgfeesmanualfee property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFMSGFEESMANUALFEE() {
        return fmsgfeesmanualfee;
    }

    /**
     * Sets the value of the fmsgfeesmanualfee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFMSGFEESMANUALFEE(Integer value) {
        this.fmsgfeesmanualfee = value;
    }

    /**
     * Gets the value of the fmsgfeesfeeformulaname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESFEEFORMULANAME() {
        return fmsgfeesfeeformulaname;
    }

    /**
     * Sets the value of the fmsgfeesfeeformulaname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESFEEFORMULANAME(String value) {
        this.fmsgfeesfeeformulaname = value;
    }

    /**
     * Gets the value of the fmsgfeesfeetypename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESFEETYPENAME() {
        return fmsgfeesfeetypename;
    }

    /**
     * Sets the value of the fmsgfeesfeetypename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESFEETYPENAME(String value) {
        this.fmsgfeesfeetypename = value;
    }

    /**
     * Gets the value of the fmsgfeesdeductfrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESDEDUCTFROM() {
        return fmsgfeesdeductfrom;
    }

    /**
     * Sets the value of the fmsgfeesdeductfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESDEDUCTFROM(String value) {
        this.fmsgfeesdeductfrom = value;
    }

    /**
     * Gets the value of the fmsgfeesfeeaccamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFMSGFEESFEEACCAMOUNT() {
        return fmsgfeesfeeaccamount;
    }

    /**
     * Sets the value of the fmsgfeesfeeaccamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFMSGFEESFEEACCAMOUNT(BigDecimal value) {
        this.fmsgfeesfeeaccamount = value;
    }

    /**
     * Gets the value of the fmsgfeesfeeaccamtrate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFMSGFEESFEEACCAMTRATE() {
        return fmsgfeesfeeaccamtrate;
    }

    /**
     * Sets the value of the fmsgfeesfeeaccamtrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFMSGFEESFEEACCAMTRATE(BigDecimal value) {
        this.fmsgfeesfeeaccamtrate = value;
    }

    /**
     * Gets the value of the fmsgfeesfeeamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFMSGFEESFEEAMOUNT() {
        return fmsgfeesfeeamount;
    }

    /**
     * Sets the value of the fmsgfeesfeeamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFMSGFEESFEEAMOUNT(BigDecimal value) {
        this.fmsgfeesfeeamount = value;
    }

    /**
     * Gets the value of the fmsgfeesfeeamtinpmtccy property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFMSGFEESFEEAMTINPMTCCY() {
        return fmsgfeesfeeamtinpmtccy;
    }

    /**
     * Sets the value of the fmsgfeesfeeamtinpmtccy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFMSGFEESFEEAMTINPMTCCY(BigDecimal value) {
        this.fmsgfeesfeeamtinpmtccy = value;
    }

    /**
     * Gets the value of the fmsgfeesfeeapply property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESFEEAPPLY() {
        return fmsgfeesfeeapply;
    }

    /**
     * Sets the value of the fmsgfeesfeeapply property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESFEEAPPLY(String value) {
        this.fmsgfeesfeeapply = value;
    }

    /**
     * Gets the value of the fmsgfeesfeebaseamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFMSGFEESFEEBASEAMOUNT() {
        return fmsgfeesfeebaseamount;
    }

    /**
     * Sets the value of the fmsgfeesfeebaseamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFMSGFEESFEEBASEAMOUNT(BigDecimal value) {
        this.fmsgfeesfeebaseamount = value;
    }

    /**
     * Gets the value of the fmsgfeesfeecurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESFEECURRENCY() {
        return fmsgfeesfeecurrency;
    }

    /**
     * Sets the value of the fmsgfeesfeecurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESFEECURRENCY(String value) {
        this.fmsgfeesfeecurrency = value;
    }

    /**
     * Gets the value of the fmsgfeesfeeformulauid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESFEEFORMULAUID() {
        return fmsgfeesfeeformulauid;
    }

    /**
     * Sets the value of the fmsgfeesfeeformulauid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESFEEFORMULAUID(String value) {
        this.fmsgfeesfeeformulauid = value;
    }

    /**
     * Gets the value of the fmsgfeesfeemonitor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESFEEMONITOR() {
        return fmsgfeesfeemonitor;
    }

    /**
     * Sets the value of the fmsgfeesfeemonitor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESFEEMONITOR(String value) {
        this.fmsgfeesfeemonitor = value;
    }

    /**
     * Gets the value of the fmsgfeesfeepnlacccur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESFEEPNLACCCUR() {
        return fmsgfeesfeepnlacccur;
    }

    /**
     * Sets the value of the fmsgfeesfeepnlacccur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESFEEPNLACCCUR(String value) {
        this.fmsgfeesfeepnlacccur = value;
    }

    /**
     * Gets the value of the fmsgfeesfeepnlaccno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESFEEPNLACCNO() {
        return fmsgfeesfeepnlaccno;
    }

    /**
     * Sets the value of the fmsgfeesfeepnlaccno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESFEEPNLACCNO(String value) {
        this.fmsgfeesfeepnlaccno = value;
    }

    /**
     * Gets the value of the fmsgfeesfeepnlamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFMSGFEESFEEPNLAMOUNT() {
        return fmsgfeesfeepnlamount;
    }

    /**
     * Sets the value of the fmsgfeesfeepnlamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFMSGFEESFEEPNLAMOUNT(BigDecimal value) {
        this.fmsgfeesfeepnlamount = value;
    }

    /**
     * Gets the value of the fmsgfeesfeetypeuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESFEETYPEUID() {
        return fmsgfeesfeetypeuid;
    }

    /**
     * Sets the value of the fmsgfeesfeetypeuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESFEETYPEUID(String value) {
        this.fmsgfeesfeetypeuid = value;
    }

    /**
     * Gets the value of the fmsgfeesorigfeeamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFMSGFEESORIGFEEAMOUNT() {
        return fmsgfeesorigfeeamount;
    }

    /**
     * Sets the value of the fmsgfeesorigfeeamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFMSGFEESORIGFEEAMOUNT(BigDecimal value) {
        this.fmsgfeesorigfeeamount = value;
    }

    /**
     * Gets the value of the fmsgfeespayingparty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESPAYINGPARTY() {
        return fmsgfeespayingparty;
    }

    /**
     * Sets the value of the fmsgfeespayingparty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESPAYINGPARTY(String value) {
        this.fmsgfeespayingparty = value;
    }

    /**
     * Gets the value of the fmsgfeespnlaccoffice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESPNLACCOFFICE() {
        return fmsgfeespnlaccoffice;
    }

    /**
     * Sets the value of the fmsgfeespnlaccoffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESPNLACCOFFICE(String value) {
        this.fmsgfeespnlaccoffice = value;
    }

    /**
     * Gets the value of the fmsgfeespnlpostingsts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESPNLPOSTINGSTS() {
        return fmsgfeespnlpostingsts;
    }

    /**
     * Sets the value of the fmsgfeespnlpostingsts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESPNLPOSTINGSTS(String value) {
        this.fmsgfeespnlpostingsts = value;
    }

    /**
     * Gets the value of the fmsgfeesunwindfee property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFMSGFEESUNWINDFEE() {
        return fmsgfeesunwindfee;
    }

    /**
     * Sets the value of the fmsgfeesunwindfee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFMSGFEESUNWINDFEE(Boolean value) {
        this.fmsgfeesunwindfee = value;
    }

    /**
     * Gets the value of the fmsgfeestaxamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFMSGFEESTAXAMOUNT() {
        return fmsgfeestaxamount;
    }

    /**
     * Sets the value of the fmsgfeestaxamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFMSGFEESTAXAMOUNT(BigDecimal value) {
        this.fmsgfeestaxamount = value;
    }

    /**
     * Gets the value of the fmsgfeestaxbaseamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFMSGFEESTAXBASEAMOUNT() {
        return fmsgfeestaxbaseamount;
    }

    /**
     * Sets the value of the fmsgfeestaxbaseamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFMSGFEESTAXBASEAMOUNT(BigDecimal value) {
        this.fmsgfeestaxbaseamount = value;
    }

    /**
     * Gets the value of the fmsgfeesrebate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFMSGFEESREBATE() {
        return fmsgfeesrebate;
    }

    /**
     * Sets the value of the fmsgfeesrebate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFMSGFEESREBATE(BigDecimal value) {
        this.fmsgfeesrebate = value;
    }

    /**
     * Gets the value of the fmsgfeesbase2FEEACCTRATE property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFMSGFEESBASE2FEEACCTRATE() {
        return fmsgfeesbase2FEEACCTRATE;
    }

    /**
     * Sets the value of the fmsgfeesbase2FEEACCTRATE property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFMSGFEESBASE2FEEACCTRATE(BigDecimal value) {
        this.fmsgfeesbase2FEEACCTRATE = value;
    }

    /**
     * Gets the value of the fmsgfeesbase2FEEACCTVER property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFMSGFEESBASE2FEEACCTVER() {
        return fmsgfeesbase2FEEACCTVER;
    }

    /**
     * Sets the value of the fmsgfeesbase2FEEACCTVER property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFMSGFEESBASE2FEEACCTVER(BigDecimal value) {
        this.fmsgfeesbase2FEEACCTVER = value;
    }

    /**
     * Gets the value of the fmsgfeesbaseamtratever property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFMSGFEESBASEAMTRATEVER() {
        return fmsgfeesbaseamtratever;
    }

    /**
     * Sets the value of the fmsgfeesbaseamtratever property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFMSGFEESBASEAMTRATEVER(BigDecimal value) {
        this.fmsgfeesbaseamtratever = value;
    }

    /**
     * Gets the value of the fmsgfeesfeebasecurrate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFMSGFEESFEEBASECURRATE() {
        return fmsgfeesfeebasecurrate;
    }

    /**
     * Sets the value of the fmsgfeesfeebasecurrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFMSGFEESFEEBASECURRATE(BigDecimal value) {
        this.fmsgfeesfeebasecurrate = value;
    }

    /**
     * Gets the value of the fmsgfeestaxamtpnlccy property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFMSGFEESTAXAMTPNLCCY() {
        return fmsgfeestaxamtpnlccy;
    }

    /**
     * Sets the value of the fmsgfeestaxamtpnlccy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFMSGFEESTAXAMTPNLCCY(BigDecimal value) {
        this.fmsgfeestaxamtpnlccy = value;
    }

    /**
     * Gets the value of the fmsgfeestaxbasecurrate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFMSGFEESTAXBASECURRATE() {
        return fmsgfeestaxbasecurrate;
    }

    /**
     * Sets the value of the fmsgfeestaxbasecurrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFMSGFEESTAXBASECURRATE(BigDecimal value) {
        this.fmsgfeestaxbasecurrate = value;
    }

    /**
     * Gets the value of the fmsgfeestaxfrompayment property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFMSGFEESTAXFROMPAYMENT() {
        return fmsgfeestaxfrompayment;
    }

    /**
     * Sets the value of the fmsgfeestaxfrompayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFMSGFEESTAXFROMPAYMENT(Integer value) {
        this.fmsgfeestaxfrompayment = value;
    }

    /**
     * Gets the value of the fmsgfeestaxontaxamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFMSGFEESTAXONTAXAMOUNT() {
        return fmsgfeestaxontaxamount;
    }

    /**
     * Sets the value of the fmsgfeestaxontaxamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFMSGFEESTAXONTAXAMOUNT(BigDecimal value) {
        this.fmsgfeestaxontaxamount = value;
    }

    /**
     * Gets the value of the fmsgfeestaxpnlacct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESTAXPNLACCT() {
        return fmsgfeestaxpnlacct;
    }

    /**
     * Sets the value of the fmsgfeestaxpnlacct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESTAXPNLACCT(String value) {
        this.fmsgfeestaxpnlacct = value;
    }

    /**
     * Gets the value of the fmsgfeestaxpnlacctoffice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESTAXPNLACCTOFFICE() {
        return fmsgfeestaxpnlacctoffice;
    }

    /**
     * Sets the value of the fmsgfeestaxpnlacctoffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESTAXPNLACCTOFFICE(String value) {
        this.fmsgfeestaxpnlacctoffice = value;
    }

    /**
     * Gets the value of the fmsgfeestaxname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESTAXNAME() {
        return fmsgfeestaxname;
    }

    /**
     * Sets the value of the fmsgfeestaxname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESTAXNAME(String value) {
        this.fmsgfeestaxname = value;
    }

    /**
     * Gets the value of the fmsgfeestaxpnlacctccy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESTAXPNLACCTCCY() {
        return fmsgfeestaxpnlacctccy;
    }

    /**
     * Sets the value of the fmsgfeestaxpnlacctccy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESTAXPNLACCTCCY(String value) {
        this.fmsgfeestaxpnlacctccy = value;
    }

    /**
     * Gets the value of the fmsgfeestaxtopnlacdt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESTAXTOPNLACDT() {
        return fmsgfeestaxtopnlacdt;
    }

    /**
     * Sets the value of the fmsgfeestaxtopnlacdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESTAXTOPNLACDT(String value) {
        this.fmsgfeestaxtopnlacdt = value;
    }

    /**
     * Gets the value of the fmsgfeestaxtopnlccyrate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFMSGFEESTAXTOPNLCCYRATE() {
        return fmsgfeestaxtopnlccyrate;
    }

    /**
     * Sets the value of the fmsgfeestaxtopnlccyrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFMSGFEESTAXTOPNLCCYRATE(BigDecimal value) {
        this.fmsgfeestaxtopnlccyrate = value;
    }

    /**
     * Gets the value of the fmsgfeestaxtopnlccyver property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFMSGFEESTAXTOPNLCCYVER() {
        return fmsgfeestaxtopnlccyver;
    }

    /**
     * Sets the value of the fmsgfeestaxtopnlccyver property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFMSGFEESTAXTOPNLCCYVER(BigDecimal value) {
        this.fmsgfeestaxtopnlccyver = value;
    }

    /**
     * Gets the value of the fmsgfeespnlaccno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESPNLACCNO() {
        return fmsgfeespnlaccno;
    }

    /**
     * Sets the value of the fmsgfeespnlaccno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESPNLACCNO(String value) {
        this.fmsgfeespnlaccno = value;
    }

    /**
     * Gets the value of the fmsgfeesmid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESMID() {
        return fmsgfeesmid;
    }

    /**
     * Sets the value of the fmsgfeesmid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESMID(String value) {
        this.fmsgfeesmid = value;
    }

    /**
     * Gets the value of the fmsgfeesfeepostntryid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESFEEPOSTNTRYID() {
        return fmsgfeesfeepostntryid;
    }

    /**
     * Sets the value of the fmsgfeesfeepostntryid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESFEEPOSTNTRYID(String value) {
        this.fmsgfeesfeepostntryid = value;
    }

    /**
     * Gets the value of the fmsgfeespnlpostntryid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESPNLPOSTNTRYID() {
        return fmsgfeespnlpostntryid;
    }

    /**
     * Sets the value of the fmsgfeespnlpostntryid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESPNLPOSTNTRYID(String value) {
        this.fmsgfeespnlpostntryid = value;
    }

    /**
     * Gets the value of the fmsgfeestxpostntryid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESTXPOSTNTRYID() {
        return fmsgfeestxpostntryid;
    }

    /**
     * Sets the value of the fmsgfeestxpostntryid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESTXPOSTNTRYID(String value) {
        this.fmsgfeestxpostntryid = value;
    }

    /**
     * Gets the value of the fmsgfeestxpnlpostntryid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESTXPNLPOSTNTRYID() {
        return fmsgfeestxpnlpostntryid;
    }

    /**
     * Sets the value of the fmsgfeestxpnlpostntryid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESTXPNLPOSTNTRYID(String value) {
        this.fmsgfeestxpnlpostntryid = value;
    }

    /**
     * Gets the value of the fmsgfeestxontaxntryid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESTXONTAXNTRYID() {
        return fmsgfeestxontaxntryid;
    }

    /**
     * Sets the value of the fmsgfeestxontaxntryid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESTXONTAXNTRYID(String value) {
        this.fmsgfeestxontaxntryid = value;
    }

    /**
     * Gets the value of the fmsgfeestxontxpnlntryid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESTXONTXPNLNTRYID() {
        return fmsgfeestxontxpnlntryid;
    }

    /**
     * Sets the value of the fmsgfeestxontxpnlntryid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESTXONTXPNLNTRYID(String value) {
        this.fmsgfeestxontxpnlntryid = value;
    }

    /**
     * Gets the value of the fmsgfeestaxprstgrate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFMSGFEESTAXPRSTGRATE() {
        return fmsgfeestaxprstgrate;
    }

    /**
     * Sets the value of the fmsgfeestaxprstgrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFMSGFEESTAXPRSTGRATE(BigDecimal value) {
        this.fmsgfeestaxprstgrate = value;
    }

    /**
     * Gets the value of the fmsgfeesfeetaxcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESFEETAXCODE() {
        return fmsgfeesfeetaxcode;
    }

    /**
     * Sets the value of the fmsgfeesfeetaxcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESFEETAXCODE(String value) {
        this.fmsgfeesfeetaxcode = value;
    }

    /**
     * Gets the value of the fmsgfeesfeetypedescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMSGFEESFEETYPEDESCRIPTION() {
        return fmsgfeesfeetypedescription;
    }

    /**
     * Sets the value of the fmsgfeesfeetypedescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMSGFEESFEETYPEDESCRIPTION(String value) {
        this.fmsgfeesfeetypedescription = value;
    }

}
