//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.28 at 09:00:52 PM CEST 
//


package org.example.model.com.fundtech.scl.commontypes;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for M_STTLM_CCY_PROFILEType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="M_STTLM_CCY_PROFILEType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="F_INSTR_CCY_DRAFT" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="F_INSTR_CCY_EURO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "M_STTLM_CCY_PROFILEType", propOrder = {

})
public class MSTTLMCCYPROFILEType {

    @XmlElement(name = "F_INSTR_CCY_DRAFT")
    protected Boolean finstrccydraft;
    @XmlElement(name = "F_INSTR_CCY_EURO")
    protected String finstrccyeuro;

    /**
     * Gets the value of the finstrccydraft property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFINSTRCCYDRAFT() {
        return finstrccydraft;
    }

    /**
     * Sets the value of the finstrccydraft property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFINSTRCCYDRAFT(Boolean value) {
        this.finstrccydraft = value;
    }

    /**
     * Gets the value of the finstrccyeuro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFINSTRCCYEURO() {
        return finstrccyeuro;
    }

    /**
     * Sets the value of the finstrccyeuro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFINSTRCCYEURO(String value) {
        this.finstrccyeuro = value;
    }

}
