//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.28 at 03:48:14 PM CEST 
//


package org.example.model.com.fundtech.scl.commontypes;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for ParseOutputModeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParseOutputModeType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://fundtech.com/SCL/CommonTypes&gt;XmlType"&gt;
 *       &lt;attribute name="pmntConversionType" type="{http://www.w3.org/2001/XMLSchema}string" default="AS-IS" /&gt;
 *       &lt;attribute name="origPmntConversionType" type="{http://www.w3.org/2001/XMLSchema}string" default="AS-IS" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@jakarta.xml.bind.annotation.XmlType(name = "ParseOutputModeType", propOrder = {
    "value"
})
public class ParseOutputModeType {

    @XmlValue
    protected org.example.model.com.fundtech.scl.commontypes.XmlType value;
    @XmlAttribute(name = "pmntConversionType")
    protected String pmntConversionType;
    @XmlAttribute(name = "origPmntConversionType")
    protected String origPmntConversionType;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link org.example.model.com.fundtech.scl.commontypes.XmlType }
     *     
     */
    public org.example.model.com.fundtech.scl.commontypes.XmlType getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.example.model.com.fundtech.scl.commontypes.XmlType }
     *     
     */
    public void setValue(org.example.model.com.fundtech.scl.commontypes.XmlType value) {
        this.value = value;
    }

    /**
     * Gets the value of the pmntConversionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmntConversionType() {
        if (pmntConversionType == null) {
            return "AS-IS";
        } else {
            return pmntConversionType;
        }
    }

    /**
     * Sets the value of the pmntConversionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmntConversionType(String value) {
        this.pmntConversionType = value;
    }

    /**
     * Gets the value of the origPmntConversionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigPmntConversionType() {
        if (origPmntConversionType == null) {
            return "AS-IS";
        } else {
            return origPmntConversionType;
        }
    }

    /**
     * Sets the value of the origPmntConversionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigPmntConversionType(String value) {
        this.origPmntConversionType = value;
    }

}
