//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.28 at 03:48:14 PM CEST 
//


package org.example.model.com.fundtech.scl.commontypes;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 *         QA Section is for internal use only
 *       
 * 
 * <p>Java class for QaInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QaInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="D_ELAPSED_TIME_MS" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="QATest2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QaInfoType", propOrder = {
    "delapsedtimems",
    "qaTest2"
})
public class QaInfoType {

    @XmlElement(name = "D_ELAPSED_TIME_MS")
    protected List<String> delapsedtimems;
    @XmlElement(name = "QATest2", required = true)
    protected String qaTest2;

    /**
     * Gets the value of the delapsedtimems property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the delapsedtimems property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDELAPSEDTIMEMS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDELAPSEDTIMEMS() {
        if (delapsedtimems == null) {
            delapsedtimems = new ArrayList<String>();
        }
        return this.delapsedtimems;
    }

    /**
     * Gets the value of the qaTest2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQATest2() {
        return qaTest2;
    }

    /**
     * Sets the value of the qaTest2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQATest2(String value) {
        this.qaTest2 = value;
    }

}
