//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.28 at 09:00:52 PM CEST 
//


package org.example.model.com.fundtech.scl.commontypes;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Tag13COtherCodeContainerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tag13COtherCodeContainerType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Tag13COtherCode" type="{http://fundtech.com/SCL/CommonTypes}Tag13COtherCodeType" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tag13COtherCodeContainerType", propOrder = {
    "tag13COtherCode"
})
public class Tag13COtherCodeContainerType {

    @XmlElement(name = "Tag13COtherCode", required = true)
    protected List<Tag13COtherCodeType> tag13COtherCode;

    /**
     * Gets the value of the tag13COtherCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the tag13COtherCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTag13COtherCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tag13COtherCodeType }
     * 
     * 
     */
    public List<Tag13COtherCodeType> getTag13COtherCode() {
        if (tag13COtherCode == null) {
            tag13COtherCode = new ArrayList<Tag13COtherCodeType>();
        }
        return this.tag13COtherCode;
    }

}
