//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.28 at 09:00:52 PM CEST 
//


package org.example.model.com.fundtech.scl.commontypes;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserMonitorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserMonitorType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="MU_SEND_TO_SCHEDULE" type="{http://fundtech.com/SCL/CommonTypes}MonitorFieldType" minOccurs="0"/&gt;
 *         &lt;element name="MU_FRAUD_FORCE_STS" type="{http://fundtech.com/SCL/CommonTypes}MonitorFieldType" minOccurs="0"/&gt;
 *         &lt;element name="MU_PARTY_LIMIT_FORCE_STS" type="{http://fundtech.com/SCL/CommonTypes}MonitorFieldType" minOccurs="0"/&gt;
 *         &lt;element name="MU_REQ_FOR_CHARGES_FORCE_STS" type="{http://fundtech.com/SCL/CommonTypes}MonitorFieldType" minOccurs="0"/&gt;
 *         &lt;element name="MU_STOP_FLAGS_OVERRIDE_STS" type="{http://fundtech.com/SCL/CommonTypes}MonitorFieldType" minOccurs="0"/&gt;
 *         &lt;element name="MU_MISSED_CUTOFF" type="{http://fundtech.com/SCL/CommonTypes}MonitorFieldType" minOccurs="0"/&gt;
 *         &lt;element name="MU_SPECIAL_INST_STS" type="{http://fundtech.com/SCL/CommonTypes}MonitorFieldType" minOccurs="0"/&gt;
 *         &lt;element name="MU_PI_FORCE_STS" type="{http://fundtech.com/SCL/CommonTypes}MonitorFieldType" minOccurs="0"/&gt;
 *         &lt;element name="MU_HANDLE_71G_GAP" type="{http://fundtech.com/SCL/CommonTypes}MonitorFieldType" minOccurs="0"/&gt;
 *         &lt;element name="MU_COMPLIANCE_FORCE_STS" type="{http://fundtech.com/SCL/CommonTypes}MonitorFieldType" minOccurs="0"/&gt;
 *         &lt;element name="MU_NSF_FORCE_STS" type="{http://fundtech.com/SCL/CommonTypes}MonitorFieldType" minOccurs="0"/&gt;
 *         &lt;element name="MU_FORCE_STANDARD_VD" type="{http://fundtech.com/SCL/CommonTypes}MonitorFieldType" minOccurs="0"/&gt;
 *         &lt;element name="MU_SET_CDT_MOP" type="{http://fundtech.com/SCL/CommonTypes}MonitorFieldType" minOccurs="0"/&gt;
 *         &lt;element name="MU_DRNSF_FORCE_IND" type="{http://fundtech.com/SCL/CommonTypes}MonitorFieldType" minOccurs="0"/&gt;
 *         &lt;element name="MU_CRNSF_FORCE_IND" type="{http://fundtech.com/SCL/CommonTypes}MonitorFieldType" minOccurs="0"/&gt;
 *         &lt;element name="MU_BIWAITQ_ACTION" type="{http://fundtech.com/SCL/CommonTypes}MonitorFieldType" minOccurs="0"/&gt;
 *         &lt;element name="MU_I_MP_REPAIR_MODE" type="{http://fundtech.com/SCL/CommonTypes}MonitorFieldType" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserMonitorType", propOrder = {

})
public class UserMonitorType {

    @XmlElement(name = "MU_SEND_TO_SCHEDULE")
    protected String musendtoschedule;
    @XmlElement(name = "MU_FRAUD_FORCE_STS")
    protected String mufraudforcests;
    @XmlElement(name = "MU_PARTY_LIMIT_FORCE_STS")
    protected String mupartylimitforcests;
    @XmlElement(name = "MU_REQ_FOR_CHARGES_FORCE_STS")
    protected String mureqforchargesforcests;
    @XmlElement(name = "MU_STOP_FLAGS_OVERRIDE_STS")
    protected String mustopflagsoverridests;
    @XmlElement(name = "MU_MISSED_CUTOFF")
    protected String mumissedcutoff;
    @XmlElement(name = "MU_SPECIAL_INST_STS")
    protected String muspecialinststs;
    @XmlElement(name = "MU_PI_FORCE_STS")
    protected String mupiforcests;
    @XmlElement(name = "MU_HANDLE_71G_GAP")
    protected String muhandle71GGAP;
    @XmlElement(name = "MU_COMPLIANCE_FORCE_STS")
    protected String mucomplianceforcests;
    @XmlElement(name = "MU_NSF_FORCE_STS")
    protected String munsfforcests;
    @XmlElement(name = "MU_FORCE_STANDARD_VD")
    protected String muforcestandardvd;
    @XmlElement(name = "MU_SET_CDT_MOP")
    protected String musetcdtmop;
    @XmlElement(name = "MU_DRNSF_FORCE_IND")
    protected String mudrnsfforceind;
    @XmlElement(name = "MU_CRNSF_FORCE_IND")
    protected String mucrnsfforceind;
    @XmlElement(name = "MU_BIWAITQ_ACTION")
    protected String mubiwaitqaction;
    @XmlElement(name = "MU_I_MP_REPAIR_MODE")
    protected String muimprepairmode;

    /**
     * Gets the value of the musendtoschedule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMUSENDTOSCHEDULE() {
        return musendtoschedule;
    }

    /**
     * Sets the value of the musendtoschedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMUSENDTOSCHEDULE(String value) {
        this.musendtoschedule = value;
    }

    /**
     * Gets the value of the mufraudforcests property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMUFRAUDFORCESTS() {
        return mufraudforcests;
    }

    /**
     * Sets the value of the mufraudforcests property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMUFRAUDFORCESTS(String value) {
        this.mufraudforcests = value;
    }

    /**
     * Gets the value of the mupartylimitforcests property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMUPARTYLIMITFORCESTS() {
        return mupartylimitforcests;
    }

    /**
     * Sets the value of the mupartylimitforcests property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMUPARTYLIMITFORCESTS(String value) {
        this.mupartylimitforcests = value;
    }

    /**
     * Gets the value of the mureqforchargesforcests property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMUREQFORCHARGESFORCESTS() {
        return mureqforchargesforcests;
    }

    /**
     * Sets the value of the mureqforchargesforcests property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMUREQFORCHARGESFORCESTS(String value) {
        this.mureqforchargesforcests = value;
    }

    /**
     * Gets the value of the mustopflagsoverridests property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMUSTOPFLAGSOVERRIDESTS() {
        return mustopflagsoverridests;
    }

    /**
     * Sets the value of the mustopflagsoverridests property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMUSTOPFLAGSOVERRIDESTS(String value) {
        this.mustopflagsoverridests = value;
    }

    /**
     * Gets the value of the mumissedcutoff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMUMISSEDCUTOFF() {
        return mumissedcutoff;
    }

    /**
     * Sets the value of the mumissedcutoff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMUMISSEDCUTOFF(String value) {
        this.mumissedcutoff = value;
    }

    /**
     * Gets the value of the muspecialinststs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMUSPECIALINSTSTS() {
        return muspecialinststs;
    }

    /**
     * Sets the value of the muspecialinststs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMUSPECIALINSTSTS(String value) {
        this.muspecialinststs = value;
    }

    /**
     * Gets the value of the mupiforcests property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMUPIFORCESTS() {
        return mupiforcests;
    }

    /**
     * Sets the value of the mupiforcests property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMUPIFORCESTS(String value) {
        this.mupiforcests = value;
    }

    /**
     * Gets the value of the muhandle71GGAP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMUHANDLE71GGAP() {
        return muhandle71GGAP;
    }

    /**
     * Sets the value of the muhandle71GGAP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMUHANDLE71GGAP(String value) {
        this.muhandle71GGAP = value;
    }

    /**
     * Gets the value of the mucomplianceforcests property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMUCOMPLIANCEFORCESTS() {
        return mucomplianceforcests;
    }

    /**
     * Sets the value of the mucomplianceforcests property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMUCOMPLIANCEFORCESTS(String value) {
        this.mucomplianceforcests = value;
    }

    /**
     * Gets the value of the munsfforcests property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMUNSFFORCESTS() {
        return munsfforcests;
    }

    /**
     * Sets the value of the munsfforcests property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMUNSFFORCESTS(String value) {
        this.munsfforcests = value;
    }

    /**
     * Gets the value of the muforcestandardvd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMUFORCESTANDARDVD() {
        return muforcestandardvd;
    }

    /**
     * Sets the value of the muforcestandardvd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMUFORCESTANDARDVD(String value) {
        this.muforcestandardvd = value;
    }

    /**
     * Gets the value of the musetcdtmop property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMUSETCDTMOP() {
        return musetcdtmop;
    }

    /**
     * Sets the value of the musetcdtmop property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMUSETCDTMOP(String value) {
        this.musetcdtmop = value;
    }

    /**
     * Gets the value of the mudrnsfforceind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMUDRNSFFORCEIND() {
        return mudrnsfforceind;
    }

    /**
     * Sets the value of the mudrnsfforceind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMUDRNSFFORCEIND(String value) {
        this.mudrnsfforceind = value;
    }

    /**
     * Gets the value of the mucrnsfforceind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMUCRNSFFORCEIND() {
        return mucrnsfforceind;
    }

    /**
     * Sets the value of the mucrnsfforceind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMUCRNSFFORCEIND(String value) {
        this.mucrnsfforceind = value;
    }

    /**
     * Gets the value of the mubiwaitqaction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMUBIWAITQACTION() {
        return mubiwaitqaction;
    }

    /**
     * Sets the value of the mubiwaitqaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMUBIWAITQACTION(String value) {
        this.mubiwaitqaction = value;
    }

    /**
     * Gets the value of the muimprepairmode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMUIMPREPAIRMODE() {
        return muimprepairmode;
    }

    /**
     * Sets the value of the muimprepairmode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMUIMPREPAIRMODE(String value) {
        this.muimprepairmode = value;
    }

}
