//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.28 at 09:00:52 PM CEST 
//


package org.example.model.com.fundtech.scl.commontypes;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 *         Example:
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;UserDefinedFields xmlns:tns="http://fundtech.com/SCL/CommonTypes" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&#13;
 *           &lt;System&gt;&#13;
 *             &lt;UDF5&gt;Value&lt;/UDF5&gt;&#13;
 *           &lt;/System&gt;&#13;
 *           &lt;Office code="OFFICE DEFAULT CUST CODE"&gt;&lt;UDF1&gt;Value&lt;/UDF1&gt;&lt;BANK_REPORTING_CD&gt;Value&lt;/BANK_REPORTING_CD&gt;&lt;UDF2&gt;Value&lt;/UDF2&gt;&#13;
 *           &lt;/Office&gt;&#13;
 *           &lt;Customer code="PAYMENT proprietary ID"&gt;&lt;LOGICAL_FIELD_NAME4&gt;Value&lt;/LOGICAL_FIELD_NAME4&gt;&lt;CUSTROMER_REPORTING_CD&gt;Value&lt;/CUSTROMER_REPORTING_CD&gt;&lt;LOGICAL_FIELD_NAME6&gt;Value&lt;/LOGICAL_FIELD_NAME6&gt;&#13;
 *           &lt;/Customer&gt;&#13;
 *         &lt;/UserDefinedFields&gt;
 * </pre>
 * 
 *       
 * 
 * <p>Java class for UserDefinedFieldsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserDefinedFieldsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="System" type="{http://fundtech.com/SCL/CommonTypes}SystemUDFContainerType" minOccurs="0"/&gt;
 *         &lt;element name="Office" type="{http://fundtech.com/SCL/CommonTypes}OfficeUDFContainerType" minOccurs="0"/&gt;
 *         &lt;element name="Customer" type="{http://fundtech.com/SCL/CommonTypes}UDFContainerType" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserDefinedFieldsType", propOrder = {

})
public class UserDefinedFieldsType {

    @XmlElement(name = "System")
    protected SystemUDFContainerType system;
    @XmlElement(name = "Office")
    protected OfficeUDFContainerType office;
    @XmlElement(name = "Customer")
    protected UDFContainerType customer;

    /**
     * Gets the value of the system property.
     * 
     * @return
     *     possible object is
     *     {@link SystemUDFContainerType }
     *     
     */
    public SystemUDFContainerType getSystem() {
        return system;
    }

    /**
     * Sets the value of the system property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemUDFContainerType }
     *     
     */
    public void setSystem(SystemUDFContainerType value) {
        this.system = value;
    }

    /**
     * Gets the value of the office property.
     * 
     * @return
     *     possible object is
     *     {@link OfficeUDFContainerType }
     *     
     */
    public OfficeUDFContainerType getOffice() {
        return office;
    }

    /**
     * Sets the value of the office property.
     * 
     * @param value
     *     allowed object is
     *     {@link OfficeUDFContainerType }
     *     
     */
    public void setOffice(OfficeUDFContainerType value) {
        this.office = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link UDFContainerType }
     *     
     */
    public UDFContainerType getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link UDFContainerType }
     *     
     */
    public void setCustomer(UDFContainerType value) {
        this.customer = value;
    }

}
